/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// Defines ActionType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ActionType
    {
        /// <summary>
        /// Enum Movement for value: movement
        /// </summary>
        [EnumMember(Value = "movement")]
        Movement = 1,

        /// <summary>
        /// Enum Fight for value: fight
        /// </summary>
        [EnumMember(Value = "fight")]
        Fight = 2,

        /// <summary>
        /// Enum MultiFight for value: multi_fight
        /// </summary>
        [EnumMember(Value = "multi_fight")]
        MultiFight = 3,

        /// <summary>
        /// Enum Crafting for value: crafting
        /// </summary>
        [EnumMember(Value = "crafting")]
        Crafting = 4,

        /// <summary>
        /// Enum Gathering for value: gathering
        /// </summary>
        [EnumMember(Value = "gathering")]
        Gathering = 5,

        /// <summary>
        /// Enum BuyGe for value: buy_ge
        /// </summary>
        [EnumMember(Value = "buy_ge")]
        BuyGe = 6,

        /// <summary>
        /// Enum SellGe for value: sell_ge
        /// </summary>
        [EnumMember(Value = "sell_ge")]
        SellGe = 7,

        /// <summary>
        /// Enum CreateBuyOrderGe for value: create_buy_order_ge
        /// </summary>
        [EnumMember(Value = "create_buy_order_ge")]
        CreateBuyOrderGe = 8,

        /// <summary>
        /// Enum FillBuyOrderGe for value: fill_buy_order_ge
        /// </summary>
        [EnumMember(Value = "fill_buy_order_ge")]
        FillBuyOrderGe = 9,

        /// <summary>
        /// Enum BuyNpc for value: buy_npc
        /// </summary>
        [EnumMember(Value = "buy_npc")]
        BuyNpc = 10,

        /// <summary>
        /// Enum SellNpc for value: sell_npc
        /// </summary>
        [EnumMember(Value = "sell_npc")]
        SellNpc = 11,

        /// <summary>
        /// Enum CancelGe for value: cancel_ge
        /// </summary>
        [EnumMember(Value = "cancel_ge")]
        CancelGe = 12,

        /// <summary>
        /// Enum DeleteItem for value: delete_item
        /// </summary>
        [EnumMember(Value = "delete_item")]
        DeleteItem = 13,

        /// <summary>
        /// Enum DepositItem for value: deposit_item
        /// </summary>
        [EnumMember(Value = "deposit_item")]
        DepositItem = 14,

        /// <summary>
        /// Enum WithdrawItem for value: withdraw_item
        /// </summary>
        [EnumMember(Value = "withdraw_item")]
        WithdrawItem = 15,

        /// <summary>
        /// Enum DepositGold for value: deposit_gold
        /// </summary>
        [EnumMember(Value = "deposit_gold")]
        DepositGold = 16,

        /// <summary>
        /// Enum WithdrawGold for value: withdraw_gold
        /// </summary>
        [EnumMember(Value = "withdraw_gold")]
        WithdrawGold = 17,

        /// <summary>
        /// Enum Equip for value: equip
        /// </summary>
        [EnumMember(Value = "equip")]
        Equip = 18,

        /// <summary>
        /// Enum Unequip for value: unequip
        /// </summary>
        [EnumMember(Value = "unequip")]
        Unequip = 19,

        /// <summary>
        /// Enum Task for value: task
        /// </summary>
        [EnumMember(Value = "task")]
        Task = 20,

        /// <summary>
        /// Enum Recycling for value: recycling
        /// </summary>
        [EnumMember(Value = "recycling")]
        Recycling = 21,

        /// <summary>
        /// Enum Rest for value: rest
        /// </summary>
        [EnumMember(Value = "rest")]
        Rest = 22,

        /// <summary>
        /// Enum Use for value: use
        /// </summary>
        [EnumMember(Value = "use")]
        Use = 23,

        /// <summary>
        /// Enum BuyBankExpansion for value: buy_bank_expansion
        /// </summary>
        [EnumMember(Value = "buy_bank_expansion")]
        BuyBankExpansion = 24,

        /// <summary>
        /// Enum GiveItem for value: give_item
        /// </summary>
        [EnumMember(Value = "give_item")]
        GiveItem = 25,

        /// <summary>
        /// Enum GiveGold for value: give_gold
        /// </summary>
        [EnumMember(Value = "give_gold")]
        GiveGold = 26,

        /// <summary>
        /// Enum ChangeSkin for value: change_skin
        /// </summary>
        [EnumMember(Value = "change_skin")]
        ChangeSkin = 27,

        /// <summary>
        /// Enum Rename for value: rename
        /// </summary>
        [EnumMember(Value = "rename")]
        Rename = 28,

        /// <summary>
        /// Enum Transition for value: transition
        /// </summary>
        [EnumMember(Value = "transition")]
        Transition = 29,

        /// <summary>
        /// Enum ClaimItem for value: claim_item
        /// </summary>
        [EnumMember(Value = "claim_item")]
        ClaimItem = 30
    }

}
