/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// ActiveEventSchema
    /// </summary>
    [DataContract(Name = "ActiveEventSchema")]
    public partial class ActiveEventSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActiveEventSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ActiveEventSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="ActiveEventSchema" /> class.
        /// </summary>
        /// <param name="name">Name of the event. (required).</param>
        /// <param name="code">Code of the event. (required).</param>
        /// <param name="map">Map of the event. (required).</param>
        /// <param name="previousMap">Previous map skin. (required).</param>
        /// <param name="duration">Duration in minutes. (required).</param>
        /// <param name="expiration">Expiration datetime. (required).</param>
        /// <param name="createdAt">Start datetime. (required).</param>
        public ActiveEventSchema(string name = default, string code = default, MapSchema map = default, MapSchema previousMap = default, int duration = default, DateTimeOffset expiration = default, DateTimeOffset createdAt = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ActiveEventSchema and cannot be null");
            }
            this.Name = name;
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new ArgumentNullException("code is a required property for ActiveEventSchema and cannot be null");
            }
            this.Code = code;
            // to ensure "map" is required (not null)
            if (map == null)
            {
                throw new ArgumentNullException("map is a required property for ActiveEventSchema and cannot be null");
            }
            this.Map = map;
            // to ensure "previousMap" is required (not null)
            if (previousMap == null)
            {
                throw new ArgumentNullException("previousMap is a required property for ActiveEventSchema and cannot be null");
            }
            this.PreviousMap = previousMap;
            this.Duration = duration;
            this.Expiration = expiration;
            this.CreatedAt = createdAt;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Name of the event.
        /// </summary>
        /// <value>Name of the event.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Code of the event.
        /// </summary>
        /// <value>Code of the event.</value>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public string Code { get; set; }

        /// <summary>
        /// Map of the event.
        /// </summary>
        /// <value>Map of the event.</value>
        [DataMember(Name = "map", IsRequired = true, EmitDefaultValue = true)]
        public MapSchema Map { get; set; }

        /// <summary>
        /// Previous map skin.
        /// </summary>
        /// <value>Previous map skin.</value>
        [DataMember(Name = "previous_map", IsRequired = true, EmitDefaultValue = true)]
        public MapSchema PreviousMap { get; set; }

        /// <summary>
        /// Duration in minutes.
        /// </summary>
        /// <value>Duration in minutes.</value>
        [DataMember(Name = "duration", IsRequired = true, EmitDefaultValue = true)]
        public int Duration { get; set; }

        /// <summary>
        /// Expiration datetime.
        /// </summary>
        /// <value>Expiration datetime.</value>
        [DataMember(Name = "expiration", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset Expiration { get; set; }

        /// <summary>
        /// Start datetime.
        /// </summary>
        /// <value>Start datetime.</value>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActiveEventSchema {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Map: ").Append(Map).Append("\n");
            sb.Append("  PreviousMap: ").Append(PreviousMap).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  Expiration: ").Append(Expiration).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
