/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// BadgeSchema
    /// </summary>
    [DataContract(Name = "BadgeSchema")]
    public partial class BadgeSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BadgeSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BadgeSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="BadgeSchema" /> class.
        /// </summary>
        /// <param name="code">Code of the badge. This is the badge&#39;s unique identifier (ID). (required).</param>
        /// <param name="season">Season of the badge..</param>
        /// <param name="description">Description of the badge. (required).</param>
        /// <param name="conditions">Conditions to get the badge. (required).</param>
        public BadgeSchema(string code = default, int season = default, string description = default, List<BadgeConditionSchema> conditions = default)
        {
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new ArgumentNullException("code is a required property for BadgeSchema and cannot be null");
            }
            this.Code = code;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for BadgeSchema and cannot be null");
            }
            this.Description = description;
            // to ensure "conditions" is required (not null)
            if (conditions == null)
            {
                throw new ArgumentNullException("conditions is a required property for BadgeSchema and cannot be null");
            }
            this.Conditions = conditions;
            this.Season = season;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Code of the badge. This is the badge&#39;s unique identifier (ID).
        /// </summary>
        /// <value>Code of the badge. This is the badge&#39;s unique identifier (ID).</value>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public string Code { get; set; }

        /// <summary>
        /// Season of the badge.
        /// </summary>
        /// <value>Season of the badge.</value>
        [DataMember(Name = "season", EmitDefaultValue = false)]
        public int Season { get; set; }

        /// <summary>
        /// Description of the badge.
        /// </summary>
        /// <value>Description of the badge.</value>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Conditions to get the badge.
        /// </summary>
        /// <value>Conditions to get the badge.</value>
        [DataMember(Name = "conditions", IsRequired = true, EmitDefaultValue = true)]
        public List<BadgeConditionSchema> Conditions { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BadgeSchema {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Season: ").Append(Season).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Conditions: ").Append(Conditions).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
