/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// BankSchema
    /// </summary>
    [DataContract(Name = "BankSchema")]
    public partial class BankSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BankSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BankSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="BankSchema" /> class.
        /// </summary>
        /// <param name="slots">Maximum slots in your bank. (required).</param>
        /// <param name="expansions">Bank expansions. (required).</param>
        /// <param name="nextExpansionCost">Next expansion cost. (required).</param>
        /// <param name="gold">Quantity of gold in your bank. (required).</param>
        public BankSchema(int slots = default, int expansions = default, int nextExpansionCost = default, int gold = default)
        {
            this.Slots = slots;
            this.Expansions = expansions;
            this.NextExpansionCost = nextExpansionCost;
            this.Gold = gold;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Maximum slots in your bank.
        /// </summary>
        /// <value>Maximum slots in your bank.</value>
        [DataMember(Name = "slots", IsRequired = true, EmitDefaultValue = true)]
        public int Slots { get; set; }

        /// <summary>
        /// Bank expansions.
        /// </summary>
        /// <value>Bank expansions.</value>
        [DataMember(Name = "expansions", IsRequired = true, EmitDefaultValue = true)]
        public int Expansions { get; set; }

        /// <summary>
        /// Next expansion cost.
        /// </summary>
        /// <value>Next expansion cost.</value>
        [DataMember(Name = "next_expansion_cost", IsRequired = true, EmitDefaultValue = true)]
        public int NextExpansionCost { get; set; }

        /// <summary>
        /// Quantity of gold in your bank.
        /// </summary>
        /// <value>Quantity of gold in your bank.</value>
        [DataMember(Name = "gold", IsRequired = true, EmitDefaultValue = true)]
        public int Gold { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BankSchema {\n");
            sb.Append("  Slots: ").Append(Slots).Append("\n");
            sb.Append("  Expansions: ").Append(Expansions).Append("\n");
            sb.Append("  NextExpansionCost: ").Append(NextExpansionCost).Append("\n");
            sb.Append("  Gold: ").Append(Gold).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Slots (int) minimum
            if (this.Slots < (int)0)
            {
                yield return new ValidationResult("Invalid value for Slots, must be a value greater than or equal to 0.", new [] { "Slots" });
            }

            // Expansions (int) minimum
            if (this.Expansions < (int)0)
            {
                yield return new ValidationResult("Invalid value for Expansions, must be a value greater than or equal to 0.", new [] { "Expansions" });
            }

            // NextExpansionCost (int) minimum
            if (this.NextExpansionCost < (int)0)
            {
                yield return new ValidationResult("Invalid value for NextExpansionCost, must be a value greater than or equal to 0.", new [] { "NextExpansionCost" });
            }

            // Gold (int) minimum
            if (this.Gold < (int)0)
            {
                yield return new ValidationResult("Invalid value for Gold, must be a value greater than or equal to 0.", new [] { "Gold" });
            }

            yield break;
        }
    }

}
