/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// CharacterFightDataSchema
    /// </summary>
    [DataContract(Name = "CharacterFightDataSchema")]
    public partial class CharacterFightDataSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CharacterFightDataSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CharacterFightDataSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="CharacterFightDataSchema" /> class.
        /// </summary>
        /// <param name="cooldown">Cooldown details. (required).</param>
        /// <param name="fight">Character fight details. (required).</param>
        /// <param name="characters">All characters involved. (required).</param>
        public CharacterFightDataSchema(CooldownSchema cooldown = default, CharacterFightSchema fight = default, List<CharacterSchema> characters = default)
        {
            // to ensure "cooldown" is required (not null)
            if (cooldown == null)
            {
                throw new ArgumentNullException("cooldown is a required property for CharacterFightDataSchema and cannot be null");
            }
            this.Cooldown = cooldown;
            // to ensure "fight" is required (not null)
            if (fight == null)
            {
                throw new ArgumentNullException("fight is a required property for CharacterFightDataSchema and cannot be null");
            }
            this.Fight = fight;
            // to ensure "characters" is required (not null)
            if (characters == null)
            {
                throw new ArgumentNullException("characters is a required property for CharacterFightDataSchema and cannot be null");
            }
            this.Characters = characters;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Cooldown details.
        /// </summary>
        /// <value>Cooldown details.</value>
        [DataMember(Name = "cooldown", IsRequired = true, EmitDefaultValue = true)]
        public CooldownSchema Cooldown { get; set; }

        /// <summary>
        /// Character fight details.
        /// </summary>
        /// <value>Character fight details.</value>
        [DataMember(Name = "fight", IsRequired = true, EmitDefaultValue = true)]
        public CharacterFightSchema Fight { get; set; }

        /// <summary>
        /// All characters involved.
        /// </summary>
        /// <value>All characters involved.</value>
        [DataMember(Name = "characters", IsRequired = true, EmitDefaultValue = true)]
        public List<CharacterSchema> Characters { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CharacterFightDataSchema {\n");
            sb.Append("  Cooldown: ").Append(Cooldown).Append("\n");
            sb.Append("  Fight: ").Append(Fight).Append("\n");
            sb.Append("  Characters: ").Append(Characters).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
