/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// Defines CharacterSkin
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CharacterSkin
    {
        /// <summary>
        /// Enum Men1 for value: men1
        /// </summary>
        [EnumMember(Value = "men1")]
        Men1 = 1,

        /// <summary>
        /// Enum Men2 for value: men2
        /// </summary>
        [EnumMember(Value = "men2")]
        Men2 = 2,

        /// <summary>
        /// Enum Men3 for value: men3
        /// </summary>
        [EnumMember(Value = "men3")]
        Men3 = 3,

        /// <summary>
        /// Enum Women1 for value: women1
        /// </summary>
        [EnumMember(Value = "women1")]
        Women1 = 4,

        /// <summary>
        /// Enum Women2 for value: women2
        /// </summary>
        [EnumMember(Value = "women2")]
        Women2 = 5,

        /// <summary>
        /// Enum Women3 for value: women3
        /// </summary>
        [EnumMember(Value = "women3")]
        Women3 = 6,

        /// <summary>
        /// Enum Corrupted1 for value: corrupted1
        /// </summary>
        [EnumMember(Value = "corrupted1")]
        Corrupted1 = 7,

        /// <summary>
        /// Enum Zombie1 for value: zombie1
        /// </summary>
        [EnumMember(Value = "zombie1")]
        Zombie1 = 8,

        /// <summary>
        /// Enum Marauder1 for value: marauder1
        /// </summary>
        [EnumMember(Value = "marauder1")]
        Marauder1 = 9
    }

}
