/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// CombatSimulationDataSchema
    /// </summary>
    [DataContract(Name = "CombatSimulationDataSchema")]
    public partial class CombatSimulationDataSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CombatSimulationDataSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CombatSimulationDataSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="CombatSimulationDataSchema" /> class.
        /// </summary>
        /// <param name="results">Results from each combat iteration. (required).</param>
        /// <param name="wins">Total number of victories. (required).</param>
        /// <param name="losses">Total number of defeats. (required).</param>
        /// <param name="winrate">Win rate percentage (0-100). (required).</param>
        public CombatSimulationDataSchema(List<CombatResultSchema> results = default, int wins = default, int losses = default, decimal winrate = default)
        {
            // to ensure "results" is required (not null)
            if (results == null)
            {
                throw new ArgumentNullException("results is a required property for CombatSimulationDataSchema and cannot be null");
            }
            this.Results = results;
            this.Wins = wins;
            this.Losses = losses;
            this.Winrate = winrate;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Results from each combat iteration.
        /// </summary>
        /// <value>Results from each combat iteration.</value>
        [DataMember(Name = "results", IsRequired = true, EmitDefaultValue = true)]
        public List<CombatResultSchema> Results { get; set; }

        /// <summary>
        /// Total number of victories.
        /// </summary>
        /// <value>Total number of victories.</value>
        [DataMember(Name = "wins", IsRequired = true, EmitDefaultValue = true)]
        public int Wins { get; set; }

        /// <summary>
        /// Total number of defeats.
        /// </summary>
        /// <value>Total number of defeats.</value>
        [DataMember(Name = "losses", IsRequired = true, EmitDefaultValue = true)]
        public int Losses { get; set; }

        /// <summary>
        /// Win rate percentage (0-100).
        /// </summary>
        /// <value>Win rate percentage (0-100).</value>
        [DataMember(Name = "winrate", IsRequired = true, EmitDefaultValue = true)]
        public decimal Winrate { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CombatSimulationDataSchema {\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("  Wins: ").Append(Wins).Append("\n");
            sb.Append("  Losses: ").Append(Losses).Append("\n");
            sb.Append("  Winrate: ").Append(Winrate).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
