/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// EventSchema
    /// </summary>
    [DataContract(Name = "EventSchema")]
    public partial class EventSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventSchema" /> class.
        /// </summary>
        /// <param name="name">Name of the event. (required).</param>
        /// <param name="code">Code of the event. (required).</param>
        /// <param name="content">Content of the event. (required).</param>
        /// <param name="maps">Map list of the event. (required).</param>
        /// <param name="duration">Duration in minutes. (required).</param>
        /// <param name="rate">Rate spawn of the event. (1/rate every minute) (required).</param>
        public EventSchema(string name = default, string code = default, EventContentSchema content = default, List<EventMapSchema> maps = default, int duration = default, int rate = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for EventSchema and cannot be null");
            }
            this.Name = name;
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new ArgumentNullException("code is a required property for EventSchema and cannot be null");
            }
            this.Code = code;
            // to ensure "content" is required (not null)
            if (content == null)
            {
                throw new ArgumentNullException("content is a required property for EventSchema and cannot be null");
            }
            this.Content = content;
            // to ensure "maps" is required (not null)
            if (maps == null)
            {
                throw new ArgumentNullException("maps is a required property for EventSchema and cannot be null");
            }
            this.Maps = maps;
            this.Duration = duration;
            this.Rate = rate;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Name of the event.
        /// </summary>
        /// <value>Name of the event.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Code of the event.
        /// </summary>
        /// <value>Code of the event.</value>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public string Code { get; set; }

        /// <summary>
        /// Content of the event.
        /// </summary>
        /// <value>Content of the event.</value>
        [DataMember(Name = "content", IsRequired = true, EmitDefaultValue = true)]
        public EventContentSchema Content { get; set; }

        /// <summary>
        /// Map list of the event.
        /// </summary>
        /// <value>Map list of the event.</value>
        [DataMember(Name = "maps", IsRequired = true, EmitDefaultValue = true)]
        public List<EventMapSchema> Maps { get; set; }

        /// <summary>
        /// Duration in minutes.
        /// </summary>
        /// <value>Duration in minutes.</value>
        [DataMember(Name = "duration", IsRequired = true, EmitDefaultValue = true)]
        public int Duration { get; set; }

        /// <summary>
        /// Rate spawn of the event. (1/rate every minute)
        /// </summary>
        /// <value>Rate spawn of the event. (1/rate every minute)</value>
        [DataMember(Name = "rate", IsRequired = true, EmitDefaultValue = true)]
        public int Rate { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventSchema {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  Maps: ").Append(Maps).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  Rate: ").Append(Rate).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
