/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// EventMapSchema
    /// </summary>
    [DataContract(Name = "EventMapSchema")]
    public partial class EventMapSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventMapSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventMapSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventMapSchema" /> class.
        /// </summary>
        /// <param name="mapId">ID of the map. (required).</param>
        /// <param name="x">Position X of the map. (required).</param>
        /// <param name="y">Position Y of the map. (required).</param>
        /// <param name="layer">Layer of the map. (required).</param>
        /// <param name="skin">Map skin of the map (required).</param>
        public EventMapSchema(int mapId = default, int x = default, int y = default, string layer = default, string skin = default)
        {
            this.MapId = mapId;
            this.X = x;
            this.Y = y;
            // to ensure "layer" is required (not null)
            if (layer == null)
            {
                throw new ArgumentNullException("layer is a required property for EventMapSchema and cannot be null");
            }
            this.Layer = layer;
            // to ensure "skin" is required (not null)
            if (skin == null)
            {
                throw new ArgumentNullException("skin is a required property for EventMapSchema and cannot be null");
            }
            this.Skin = skin;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// ID of the map.
        /// </summary>
        /// <value>ID of the map.</value>
        [DataMember(Name = "map_id", IsRequired = true, EmitDefaultValue = true)]
        public int MapId { get; set; }

        /// <summary>
        /// Position X of the map.
        /// </summary>
        /// <value>Position X of the map.</value>
        [DataMember(Name = "x", IsRequired = true, EmitDefaultValue = true)]
        public int X { get; set; }

        /// <summary>
        /// Position Y of the map.
        /// </summary>
        /// <value>Position Y of the map.</value>
        [DataMember(Name = "y", IsRequired = true, EmitDefaultValue = true)]
        public int Y { get; set; }

        /// <summary>
        /// Layer of the map.
        /// </summary>
        /// <value>Layer of the map.</value>
        [DataMember(Name = "layer", IsRequired = true, EmitDefaultValue = true)]
        public string Layer { get; set; }

        /// <summary>
        /// Map skin of the map
        /// </summary>
        /// <value>Map skin of the map</value>
        [DataMember(Name = "skin", IsRequired = true, EmitDefaultValue = true)]
        public string Skin { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventMapSchema {\n");
            sb.Append("  MapId: ").Append(MapId).Append("\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Layer: ").Append(Layer).Append("\n");
            sb.Append("  Skin: ").Append(Skin).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
