/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// GeOrderHistorySchema
    /// </summary>
    [DataContract(Name = "GeOrderHistorySchema")]
    public partial class GeOrderHistorySchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GeOrderHistorySchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GeOrderHistorySchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="GeOrderHistorySchema" /> class.
        /// </summary>
        /// <param name="orderId">Order id. (required).</param>
        /// <param name="seller">Seller account name. (required).</param>
        /// <param name="buyer">Buyer account name. (required).</param>
        /// <param name="code">Item code. (required).</param>
        /// <param name="quantity">Item quantity. (required).</param>
        /// <param name="price">Item price per unit. (required).</param>
        /// <param name="soldAt">Sale datetime. (required).</param>
        public GeOrderHistorySchema(string orderId = default, string seller = default, string buyer = default, string code = default, int quantity = default, int price = default, DateTimeOffset soldAt = default)
        {
            // to ensure "orderId" is required (not null)
            if (orderId == null)
            {
                throw new ArgumentNullException("orderId is a required property for GeOrderHistorySchema and cannot be null");
            }
            this.OrderId = orderId;
            // to ensure "seller" is required (not null)
            if (seller == null)
            {
                throw new ArgumentNullException("seller is a required property for GeOrderHistorySchema and cannot be null");
            }
            this.Seller = seller;
            // to ensure "buyer" is required (not null)
            if (buyer == null)
            {
                throw new ArgumentNullException("buyer is a required property for GeOrderHistorySchema and cannot be null");
            }
            this.Buyer = buyer;
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new ArgumentNullException("code is a required property for GeOrderHistorySchema and cannot be null");
            }
            this.Code = code;
            this.Quantity = quantity;
            this.Price = price;
            this.SoldAt = soldAt;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Order id.
        /// </summary>
        /// <value>Order id.</value>
        [DataMember(Name = "order_id", IsRequired = true, EmitDefaultValue = true)]
        public string OrderId { get; set; }

        /// <summary>
        /// Seller account name.
        /// </summary>
        /// <value>Seller account name.</value>
        [DataMember(Name = "seller", IsRequired = true, EmitDefaultValue = true)]
        public string Seller { get; set; }

        /// <summary>
        /// Buyer account name.
        /// </summary>
        /// <value>Buyer account name.</value>
        [DataMember(Name = "buyer", IsRequired = true, EmitDefaultValue = true)]
        public string Buyer { get; set; }

        /// <summary>
        /// Item code.
        /// </summary>
        /// <value>Item code.</value>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public string Code { get; set; }

        /// <summary>
        /// Item quantity.
        /// </summary>
        /// <value>Item quantity.</value>
        [DataMember(Name = "quantity", IsRequired = true, EmitDefaultValue = true)]
        public int Quantity { get; set; }

        /// <summary>
        /// Item price per unit.
        /// </summary>
        /// <value>Item price per unit.</value>
        [DataMember(Name = "price", IsRequired = true, EmitDefaultValue = true)]
        public int Price { get; set; }

        /// <summary>
        /// Sale datetime.
        /// </summary>
        /// <value>Sale datetime.</value>
        [DataMember(Name = "sold_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset SoldAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GeOrderHistorySchema {\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  Seller: ").Append(Seller).Append("\n");
            sb.Append("  Buyer: ").Append(Buyer).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  SoldAt: ").Append(SoldAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Quantity (int) maximum
            if (this.Quantity > (int)100)
            {
                yield return new ValidationResult("Invalid value for Quantity, must be a value less than or equal to 100.", new [] { "Quantity" });
            }

            // Quantity (int) minimum
            if (this.Quantity < (int)1)
            {
                yield return new ValidationResult("Invalid value for Quantity, must be a value greater than or equal to 1.", new [] { "Quantity" });
            }

            // Price (int) minimum
            if (this.Price < (int)1)
            {
                yield return new ValidationResult("Invalid value for Price, must be a value greater than or equal to 1.", new [] { "Price" });
            }

            yield break;
        }
    }

}
