/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// GEOrderSchema
    /// </summary>
    [DataContract(Name = "GEOrderSchema")]
    public partial class GEOrderSchema : IValidatableObject
    {

        /// <summary>
        /// Order type (sell or buy).
        /// </summary>
        /// <value>Order type (sell or buy).</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public GEOrderType? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GEOrderSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GEOrderSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="GEOrderSchema" /> class.
        /// </summary>
        /// <param name="id">Order id. (required).</param>
        /// <param name="type">Order type (sell or buy)..</param>
        /// <param name="account">Account linked to the order..</param>
        /// <param name="code">Item code. (required).</param>
        /// <param name="quantity">Item quantity. (required).</param>
        /// <param name="price">Item price per unit. (required).</param>
        /// <param name="createdAt">Order created at. (required).</param>
        public GEOrderSchema(string id = default, GEOrderType? type = default, string account = default, string code = default, int quantity = default, int price = default, DateTimeOffset createdAt = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for GEOrderSchema and cannot be null");
            }
            this.Id = id;
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new ArgumentNullException("code is a required property for GEOrderSchema and cannot be null");
            }
            this.Code = code;
            this.Quantity = quantity;
            this.Price = price;
            this.CreatedAt = createdAt;
            this.Type = type;
            this.Account = account;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Order id.
        /// </summary>
        /// <value>Order id.</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Account linked to the order.
        /// </summary>
        /// <value>Account linked to the order.</value>
        [DataMember(Name = "account", EmitDefaultValue = false)]
        public string Account { get; set; }

        /// <summary>
        /// Item code.
        /// </summary>
        /// <value>Item code.</value>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public string Code { get; set; }

        /// <summary>
        /// Item quantity.
        /// </summary>
        /// <value>Item quantity.</value>
        [DataMember(Name = "quantity", IsRequired = true, EmitDefaultValue = true)]
        public int Quantity { get; set; }

        /// <summary>
        /// Item price per unit.
        /// </summary>
        /// <value>Item price per unit.</value>
        [DataMember(Name = "price", IsRequired = true, EmitDefaultValue = true)]
        public int Price { get; set; }

        /// <summary>
        /// Order created at.
        /// </summary>
        /// <value>Order created at.</value>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GEOrderSchema {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Account: ").Append(Account).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Quantity (int) maximum
            if (this.Quantity > (int)100)
            {
                yield return new ValidationResult("Invalid value for Quantity, must be a value less than or equal to 100.", new [] { "Quantity" });
            }

            // Quantity (int) minimum
            if (this.Quantity < (int)1)
            {
                yield return new ValidationResult("Invalid value for Quantity, must be a value greater than or equal to 1.", new [] { "Quantity" });
            }

            // Price (int) minimum
            if (this.Price < (int)1)
            {
                yield return new ValidationResult("Invalid value for Price, must be a value greater than or equal to 1.", new [] { "Price" });
            }

            yield break;
        }
    }

}
