/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// GiveItemsSchema
    /// </summary>
    [DataContract(Name = "GiveItemsSchema")]
    public partial class GiveItemsSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GiveItemsSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GiveItemsSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="GiveItemsSchema" /> class.
        /// </summary>
        /// <param name="items">List of items to give (required).</param>
        /// <param name="character">Character name. The name of the character who will receive the items. (required).</param>
        public GiveItemsSchema(List<SimpleItemSchema> items = default, string character = default)
        {
            // to ensure "items" is required (not null)
            if (items == null)
            {
                throw new ArgumentNullException("items is a required property for GiveItemsSchema and cannot be null");
            }
            this.Items = items;
            // to ensure "character" is required (not null)
            if (character == null)
            {
                throw new ArgumentNullException("character is a required property for GiveItemsSchema and cannot be null");
            }
            this.Character = character;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// List of items to give
        /// </summary>
        /// <value>List of items to give</value>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = true)]
        public List<SimpleItemSchema> Items { get; set; }

        /// <summary>
        /// Character name. The name of the character who will receive the items.
        /// </summary>
        /// <value>Character name. The name of the character who will receive the items.</value>
        [DataMember(Name = "character", IsRequired = true, EmitDefaultValue = true)]
        public string Character { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GiveItemsSchema {\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  Character: ").Append(Character).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.Character != null) {
                // Character (string) pattern
                Regex regexCharacter = new Regex(@"^[a-zA-Z0-9_-]+$", RegexOptions.CultureInvariant);
                if (!regexCharacter.Match(this.Character).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Character, must match a pattern of " + regexCharacter, new [] { "Character" });
                }
            }

            yield break;
        }
    }

}
