/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// LogSchema
    /// </summary>
    [DataContract(Name = "LogSchema")]
    public partial class LogSchema : IValidatableObject
    {

        /// <summary>
        /// Type of action.
        /// </summary>
        /// <value>Type of action.</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public LogType Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="LogSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LogSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="LogSchema" /> class.
        /// </summary>
        /// <param name="character">Character name. (required).</param>
        /// <param name="account">Account character. (required).</param>
        /// <param name="type">Type of action. (required).</param>
        /// <param name="description">Description of action. (required).</param>
        /// <param name="content">content (required).</param>
        /// <param name="cooldown">Cooldown in seconds. (required).</param>
        /// <param name="cooldownExpiration">Datetime of cooldown expiration..</param>
        /// <param name="createdAt">Datetime of creation. (required).</param>
        public LogSchema(string character = default, string account = default, LogType type = default, string description = default, Object content = default, int cooldown = default, DateTimeOffset cooldownExpiration = default, DateTimeOffset createdAt = default)
        {
            // to ensure "character" is required (not null)
            if (character == null)
            {
                throw new ArgumentNullException("character is a required property for LogSchema and cannot be null");
            }
            this.Character = character;
            // to ensure "account" is required (not null)
            if (account == null)
            {
                throw new ArgumentNullException("account is a required property for LogSchema and cannot be null");
            }
            this.Account = account;
            this.Type = type;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for LogSchema and cannot be null");
            }
            this.Description = description;
            // to ensure "content" is required (not null)
            if (content == null)
            {
                throw new ArgumentNullException("content is a required property for LogSchema and cannot be null");
            }
            this.Content = content;
            this.Cooldown = cooldown;
            this.CreatedAt = createdAt;
            this.CooldownExpiration = cooldownExpiration;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Character name.
        /// </summary>
        /// <value>Character name.</value>
        [DataMember(Name = "character", IsRequired = true, EmitDefaultValue = true)]
        public string Character { get; set; }

        /// <summary>
        /// Account character.
        /// </summary>
        /// <value>Account character.</value>
        [DataMember(Name = "account", IsRequired = true, EmitDefaultValue = true)]
        public string Account { get; set; }

        /// <summary>
        /// Description of action.
        /// </summary>
        /// <value>Description of action.</value>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [DataMember(Name = "content", IsRequired = true, EmitDefaultValue = true)]
        public Object Content { get; set; }

        /// <summary>
        /// Cooldown in seconds.
        /// </summary>
        /// <value>Cooldown in seconds.</value>
        [DataMember(Name = "cooldown", IsRequired = true, EmitDefaultValue = true)]
        public int Cooldown { get; set; }

        /// <summary>
        /// Datetime of cooldown expiration.
        /// </summary>
        /// <value>Datetime of cooldown expiration.</value>
        [DataMember(Name = "cooldown_expiration", EmitDefaultValue = false)]
        public DateTimeOffset CooldownExpiration { get; set; }

        /// <summary>
        /// Datetime of creation.
        /// </summary>
        /// <value>Datetime of creation.</value>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LogSchema {\n");
            sb.Append("  Character: ").Append(Character).Append("\n");
            sb.Append("  Account: ").Append(Account).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  Cooldown: ").Append(Cooldown).Append("\n");
            sb.Append("  CooldownExpiration: ").Append(CooldownExpiration).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
