/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// Defines LogType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LogType
    {
        /// <summary>
        /// Enum Spawn for value: spawn
        /// </summary>
        [EnumMember(Value = "spawn")]
        Spawn = 1,

        /// <summary>
        /// Enum DeleteCharacter for value: delete_character
        /// </summary>
        [EnumMember(Value = "delete_character")]
        DeleteCharacter = 2,

        /// <summary>
        /// Enum Movement for value: movement
        /// </summary>
        [EnumMember(Value = "movement")]
        Movement = 3,

        /// <summary>
        /// Enum Fight for value: fight
        /// </summary>
        [EnumMember(Value = "fight")]
        Fight = 4,

        /// <summary>
        /// Enum MultiFight for value: multi_fight
        /// </summary>
        [EnumMember(Value = "multi_fight")]
        MultiFight = 5,

        /// <summary>
        /// Enum Crafting for value: crafting
        /// </summary>
        [EnumMember(Value = "crafting")]
        Crafting = 6,

        /// <summary>
        /// Enum Gathering for value: gathering
        /// </summary>
        [EnumMember(Value = "gathering")]
        Gathering = 7,

        /// <summary>
        /// Enum BuyGe for value: buy_ge
        /// </summary>
        [EnumMember(Value = "buy_ge")]
        BuyGe = 8,

        /// <summary>
        /// Enum SellGe for value: sell_ge
        /// </summary>
        [EnumMember(Value = "sell_ge")]
        SellGe = 9,

        /// <summary>
        /// Enum CreateBuyOrderGe for value: create_buy_order_ge
        /// </summary>
        [EnumMember(Value = "create_buy_order_ge")]
        CreateBuyOrderGe = 10,

        /// <summary>
        /// Enum FillBuyOrderGe for value: fill_buy_order_ge
        /// </summary>
        [EnumMember(Value = "fill_buy_order_ge")]
        FillBuyOrderGe = 11,

        /// <summary>
        /// Enum BuyNpc for value: buy_npc
        /// </summary>
        [EnumMember(Value = "buy_npc")]
        BuyNpc = 12,

        /// <summary>
        /// Enum SellNpc for value: sell_npc
        /// </summary>
        [EnumMember(Value = "sell_npc")]
        SellNpc = 13,

        /// <summary>
        /// Enum CancelGe for value: cancel_ge
        /// </summary>
        [EnumMember(Value = "cancel_ge")]
        CancelGe = 14,

        /// <summary>
        /// Enum DeleteItem for value: delete_item
        /// </summary>
        [EnumMember(Value = "delete_item")]
        DeleteItem = 15,

        /// <summary>
        /// Enum DepositItem for value: deposit_item
        /// </summary>
        [EnumMember(Value = "deposit_item")]
        DepositItem = 16,

        /// <summary>
        /// Enum WithdrawItem for value: withdraw_item
        /// </summary>
        [EnumMember(Value = "withdraw_item")]
        WithdrawItem = 17,

        /// <summary>
        /// Enum DepositGold for value: deposit_gold
        /// </summary>
        [EnumMember(Value = "deposit_gold")]
        DepositGold = 18,

        /// <summary>
        /// Enum WithdrawGold for value: withdraw_gold
        /// </summary>
        [EnumMember(Value = "withdraw_gold")]
        WithdrawGold = 19,

        /// <summary>
        /// Enum Equip for value: equip
        /// </summary>
        [EnumMember(Value = "equip")]
        Equip = 20,

        /// <summary>
        /// Enum Unequip for value: unequip
        /// </summary>
        [EnumMember(Value = "unequip")]
        Unequip = 21,

        /// <summary>
        /// Enum NewTask for value: new_task
        /// </summary>
        [EnumMember(Value = "new_task")]
        NewTask = 22,

        /// <summary>
        /// Enum TaskExchange for value: task_exchange
        /// </summary>
        [EnumMember(Value = "task_exchange")]
        TaskExchange = 23,

        /// <summary>
        /// Enum TaskCancelled for value: task_cancelled
        /// </summary>
        [EnumMember(Value = "task_cancelled")]
        TaskCancelled = 24,

        /// <summary>
        /// Enum TaskCompleted for value: task_completed
        /// </summary>
        [EnumMember(Value = "task_completed")]
        TaskCompleted = 25,

        /// <summary>
        /// Enum TaskTrade for value: task_trade
        /// </summary>
        [EnumMember(Value = "task_trade")]
        TaskTrade = 26,

        /// <summary>
        /// Enum Recycling for value: recycling
        /// </summary>
        [EnumMember(Value = "recycling")]
        Recycling = 27,

        /// <summary>
        /// Enum Rest for value: rest
        /// </summary>
        [EnumMember(Value = "rest")]
        Rest = 28,

        /// <summary>
        /// Enum Use for value: use
        /// </summary>
        [EnumMember(Value = "use")]
        Use = 29,

        /// <summary>
        /// Enum BuyBankExpansion for value: buy_bank_expansion
        /// </summary>
        [EnumMember(Value = "buy_bank_expansion")]
        BuyBankExpansion = 30,

        /// <summary>
        /// Enum Achievement for value: achievement
        /// </summary>
        [EnumMember(Value = "achievement")]
        Achievement = 31,

        /// <summary>
        /// Enum GiveItem for value: give_item
        /// </summary>
        [EnumMember(Value = "give_item")]
        GiveItem = 32,

        /// <summary>
        /// Enum GiveGold for value: give_gold
        /// </summary>
        [EnumMember(Value = "give_gold")]
        GiveGold = 33,

        /// <summary>
        /// Enum ReceiveItem for value: receive_item
        /// </summary>
        [EnumMember(Value = "receive_item")]
        ReceiveItem = 34,

        /// <summary>
        /// Enum ReceiveGold for value: receive_gold
        /// </summary>
        [EnumMember(Value = "receive_gold")]
        ReceiveGold = 35,

        /// <summary>
        /// Enum ChangeSkin for value: change_skin
        /// </summary>
        [EnumMember(Value = "change_skin")]
        ChangeSkin = 36,

        /// <summary>
        /// Enum Rename for value: rename
        /// </summary>
        [EnumMember(Value = "rename")]
        Rename = 37,

        /// <summary>
        /// Enum Transition for value: transition
        /// </summary>
        [EnumMember(Value = "transition")]
        Transition = 38,

        /// <summary>
        /// Enum ClaimItem for value: claim_item
        /// </summary>
        [EnumMember(Value = "claim_item")]
        ClaimItem = 39,

        /// <summary>
        /// Enum SandboxGiveGold for value: sandbox_give_gold
        /// </summary>
        [EnumMember(Value = "sandbox_give_gold")]
        SandboxGiveGold = 40,

        /// <summary>
        /// Enum SandboxGiveItem for value: sandbox_give_item
        /// </summary>
        [EnumMember(Value = "sandbox_give_item")]
        SandboxGiveItem = 41,

        /// <summary>
        /// Enum SandboxGiveXp for value: sandbox_give_xp
        /// </summary>
        [EnumMember(Value = "sandbox_give_xp")]
        SandboxGiveXp = 42,

        /// <summary>
        /// Enum SandboxResetAccount for value: sandbox_reset_account
        /// </summary>
        [EnumMember(Value = "sandbox_reset_account")]
        SandboxResetAccount = 43
    }

}
