/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// Defines MapContentType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MapContentType
    {
        /// <summary>
        /// Enum Monster for value: monster
        /// </summary>
        [EnumMember(Value = "monster")]
        Monster = 1,

        /// <summary>
        /// Enum Resource for value: resource
        /// </summary>
        [EnumMember(Value = "resource")]
        Resource = 2,

        /// <summary>
        /// Enum Workshop for value: workshop
        /// </summary>
        [EnumMember(Value = "workshop")]
        Workshop = 3,

        /// <summary>
        /// Enum Bank for value: bank
        /// </summary>
        [EnumMember(Value = "bank")]
        Bank = 4,

        /// <summary>
        /// Enum GrandExchange for value: grand_exchange
        /// </summary>
        [EnumMember(Value = "grand_exchange")]
        GrandExchange = 5,

        /// <summary>
        /// Enum TasksMaster for value: tasks_master
        /// </summary>
        [EnumMember(Value = "tasks_master")]
        TasksMaster = 6,

        /// <summary>
        /// Enum Npc for value: npc
        /// </summary>
        [EnumMember(Value = "npc")]
        Npc = 7
    }

}
