/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// MonsterSchema
    /// </summary>
    [DataContract(Name = "MonsterSchema")]
    public partial class MonsterSchema : IValidatableObject
    {

        /// <summary>
        /// Monster type.
        /// </summary>
        /// <value>Monster type.</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public MonsterType Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MonsterSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MonsterSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="MonsterSchema" /> class.
        /// </summary>
        /// <param name="name">Name of the monster. (required).</param>
        /// <param name="code">The code of the monster. This is the monster&#39;s unique identifier (ID). (required).</param>
        /// <param name="level">Monster level. (required).</param>
        /// <param name="type">Monster type. (required).</param>
        /// <param name="hp">Monster hit points. (required).</param>
        /// <param name="attackFire">Monster fire attack. (required).</param>
        /// <param name="attackEarth">Monster earth attack. (required).</param>
        /// <param name="attackWater">Monster water attack. (required).</param>
        /// <param name="attackAir">Monster air attack. (required).</param>
        /// <param name="resFire">Monster % fire resistance. (required).</param>
        /// <param name="resEarth">Monster % earth resistance. (required).</param>
        /// <param name="resWater">Monster % water resistance. (required).</param>
        /// <param name="resAir">Monster % air resistance. (required).</param>
        /// <param name="criticalStrike">Monster % critical strike. (required).</param>
        /// <param name="initiative">Monster initiative for turn order. (required).</param>
        /// <param name="effects">List of effects..</param>
        /// <param name="minGold">Monster minimum gold drop.  (required).</param>
        /// <param name="maxGold">Monster maximum gold drop.  (required).</param>
        /// <param name="drops">Monster drops. This is a list of items that the monster drops after killing the monster.  (required).</param>
        public MonsterSchema(string name = default, string code = default, int level = default, MonsterType type = default, int hp = default, int attackFire = default, int attackEarth = default, int attackWater = default, int attackAir = default, int resFire = default, int resEarth = default, int resWater = default, int resAir = default, int criticalStrike = default, int initiative = default, List<SimpleEffectSchema> effects = default, int minGold = default, int maxGold = default, List<DropRateSchema> drops = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for MonsterSchema and cannot be null");
            }
            this.Name = name;
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new ArgumentNullException("code is a required property for MonsterSchema and cannot be null");
            }
            this.Code = code;
            this.Level = level;
            this.Type = type;
            this.Hp = hp;
            this.AttackFire = attackFire;
            this.AttackEarth = attackEarth;
            this.AttackWater = attackWater;
            this.AttackAir = attackAir;
            this.ResFire = resFire;
            this.ResEarth = resEarth;
            this.ResWater = resWater;
            this.ResAir = resAir;
            this.CriticalStrike = criticalStrike;
            this.Initiative = initiative;
            this.MinGold = minGold;
            this.MaxGold = maxGold;
            // to ensure "drops" is required (not null)
            if (drops == null)
            {
                throw new ArgumentNullException("drops is a required property for MonsterSchema and cannot be null");
            }
            this.Drops = drops;
            this.Effects = effects;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Name of the monster.
        /// </summary>
        /// <value>Name of the monster.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The code of the monster. This is the monster&#39;s unique identifier (ID).
        /// </summary>
        /// <value>The code of the monster. This is the monster&#39;s unique identifier (ID).</value>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public string Code { get; set; }

        /// <summary>
        /// Monster level.
        /// </summary>
        /// <value>Monster level.</value>
        [DataMember(Name = "level", IsRequired = true, EmitDefaultValue = true)]
        public int Level { get; set; }

        /// <summary>
        /// Monster hit points.
        /// </summary>
        /// <value>Monster hit points.</value>
        [DataMember(Name = "hp", IsRequired = true, EmitDefaultValue = true)]
        public int Hp { get; set; }

        /// <summary>
        /// Monster fire attack.
        /// </summary>
        /// <value>Monster fire attack.</value>
        [DataMember(Name = "attack_fire", IsRequired = true, EmitDefaultValue = true)]
        public int AttackFire { get; set; }

        /// <summary>
        /// Monster earth attack.
        /// </summary>
        /// <value>Monster earth attack.</value>
        [DataMember(Name = "attack_earth", IsRequired = true, EmitDefaultValue = true)]
        public int AttackEarth { get; set; }

        /// <summary>
        /// Monster water attack.
        /// </summary>
        /// <value>Monster water attack.</value>
        [DataMember(Name = "attack_water", IsRequired = true, EmitDefaultValue = true)]
        public int AttackWater { get; set; }

        /// <summary>
        /// Monster air attack.
        /// </summary>
        /// <value>Monster air attack.</value>
        [DataMember(Name = "attack_air", IsRequired = true, EmitDefaultValue = true)]
        public int AttackAir { get; set; }

        /// <summary>
        /// Monster % fire resistance.
        /// </summary>
        /// <value>Monster % fire resistance.</value>
        [DataMember(Name = "res_fire", IsRequired = true, EmitDefaultValue = true)]
        public int ResFire { get; set; }

        /// <summary>
        /// Monster % earth resistance.
        /// </summary>
        /// <value>Monster % earth resistance.</value>
        [DataMember(Name = "res_earth", IsRequired = true, EmitDefaultValue = true)]
        public int ResEarth { get; set; }

        /// <summary>
        /// Monster % water resistance.
        /// </summary>
        /// <value>Monster % water resistance.</value>
        [DataMember(Name = "res_water", IsRequired = true, EmitDefaultValue = true)]
        public int ResWater { get; set; }

        /// <summary>
        /// Monster % air resistance.
        /// </summary>
        /// <value>Monster % air resistance.</value>
        [DataMember(Name = "res_air", IsRequired = true, EmitDefaultValue = true)]
        public int ResAir { get; set; }

        /// <summary>
        /// Monster % critical strike.
        /// </summary>
        /// <value>Monster % critical strike.</value>
        [DataMember(Name = "critical_strike", IsRequired = true, EmitDefaultValue = true)]
        public int CriticalStrike { get; set; }

        /// <summary>
        /// Monster initiative for turn order.
        /// </summary>
        /// <value>Monster initiative for turn order.</value>
        [DataMember(Name = "initiative", IsRequired = true, EmitDefaultValue = true)]
        public int Initiative { get; set; }

        /// <summary>
        /// List of effects.
        /// </summary>
        /// <value>List of effects.</value>
        [DataMember(Name = "effects", EmitDefaultValue = false)]
        public List<SimpleEffectSchema> Effects { get; set; }

        /// <summary>
        /// Monster minimum gold drop. 
        /// </summary>
        /// <value>Monster minimum gold drop. </value>
        [DataMember(Name = "min_gold", IsRequired = true, EmitDefaultValue = true)]
        public int MinGold { get; set; }

        /// <summary>
        /// Monster maximum gold drop. 
        /// </summary>
        /// <value>Monster maximum gold drop. </value>
        [DataMember(Name = "max_gold", IsRequired = true, EmitDefaultValue = true)]
        public int MaxGold { get; set; }

        /// <summary>
        /// Monster drops. This is a list of items that the monster drops after killing the monster. 
        /// </summary>
        /// <value>Monster drops. This is a list of items that the monster drops after killing the monster. </value>
        [DataMember(Name = "drops", IsRequired = true, EmitDefaultValue = true)]
        public List<DropRateSchema> Drops { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MonsterSchema {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Level: ").Append(Level).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Hp: ").Append(Hp).Append("\n");
            sb.Append("  AttackFire: ").Append(AttackFire).Append("\n");
            sb.Append("  AttackEarth: ").Append(AttackEarth).Append("\n");
            sb.Append("  AttackWater: ").Append(AttackWater).Append("\n");
            sb.Append("  AttackAir: ").Append(AttackAir).Append("\n");
            sb.Append("  ResFire: ").Append(ResFire).Append("\n");
            sb.Append("  ResEarth: ").Append(ResEarth).Append("\n");
            sb.Append("  ResWater: ").Append(ResWater).Append("\n");
            sb.Append("  ResAir: ").Append(ResAir).Append("\n");
            sb.Append("  CriticalStrike: ").Append(CriticalStrike).Append("\n");
            sb.Append("  Initiative: ").Append(Initiative).Append("\n");
            sb.Append("  Effects: ").Append(Effects).Append("\n");
            sb.Append("  MinGold: ").Append(MinGold).Append("\n");
            sb.Append("  MaxGold: ").Append(MaxGold).Append("\n");
            sb.Append("  Drops: ").Append(Drops).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
