/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// MyAccountDetails
    /// </summary>
    [DataContract(Name = "MyAccountDetails")]
    public partial class MyAccountDetails : IValidatableObject
    {

        /// <summary>
        /// Account status.
        /// </summary>
        /// <value>Account status.</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public AccountStatus Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MyAccountDetails" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MyAccountDetails()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="MyAccountDetails" /> class.
        /// </summary>
        /// <param name="username">Username. (required).</param>
        /// <param name="email">Email. (required).</param>
        /// <param name="member">Member status. (required).</param>
        /// <param name="memberExpiration">Member expiration date..</param>
        /// <param name="status">Account status. (required).</param>
        /// <param name="badges">Account badges..</param>
        /// <param name="skins">Skins owned. (required).</param>
        /// <param name="gems">Gems. (required).</param>
        /// <param name="eventToken">Event tokens for spawning events. (required).</param>
        /// <param name="achievementsPoints">Achievement points. (required).</param>
        /// <param name="banned">Banned. (required).</param>
        /// <param name="banReason">Ban reason..</param>
        public MyAccountDetails(string username = default, string email = default, bool member = default, DateTimeOffset memberExpiration = default, AccountStatus status = default, List<string> badges = default, List<string> skins = default, int gems = default, int eventToken = default, int achievementsPoints = default, bool banned = default, string banReason = default)
        {
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new ArgumentNullException("username is a required property for MyAccountDetails and cannot be null");
            }
            this.Username = username;
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for MyAccountDetails and cannot be null");
            }
            this.Email = email;
            this.Member = member;
            this.Status = status;
            // to ensure "skins" is required (not null)
            if (skins == null)
            {
                throw new ArgumentNullException("skins is a required property for MyAccountDetails and cannot be null");
            }
            this.Skins = skins;
            this.Gems = gems;
            this.EventToken = eventToken;
            this.AchievementsPoints = achievementsPoints;
            this.Banned = banned;
            this.MemberExpiration = memberExpiration;
            this.Badges = badges;
            this.BanReason = banReason;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Username.
        /// </summary>
        /// <value>Username.</value>
        [DataMember(Name = "username", IsRequired = true, EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Email.
        /// </summary>
        /// <value>Email.</value>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Member status.
        /// </summary>
        /// <value>Member status.</value>
        [DataMember(Name = "member", IsRequired = true, EmitDefaultValue = true)]
        public bool Member { get; set; }

        /// <summary>
        /// Member expiration date.
        /// </summary>
        /// <value>Member expiration date.</value>
        [DataMember(Name = "member_expiration", EmitDefaultValue = false)]
        public DateTimeOffset MemberExpiration { get; set; }

        /// <summary>
        /// Account badges.
        /// </summary>
        /// <value>Account badges.</value>
        [DataMember(Name = "badges", EmitDefaultValue = false)]
        public List<string> Badges { get; set; }

        /// <summary>
        /// Skins owned.
        /// </summary>
        /// <value>Skins owned.</value>
        [DataMember(Name = "skins", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Skins { get; set; }

        /// <summary>
        /// Gems.
        /// </summary>
        /// <value>Gems.</value>
        [DataMember(Name = "gems", IsRequired = true, EmitDefaultValue = true)]
        public int Gems { get; set; }

        /// <summary>
        /// Event tokens for spawning events.
        /// </summary>
        /// <value>Event tokens for spawning events.</value>
        [DataMember(Name = "event_token", IsRequired = true, EmitDefaultValue = true)]
        public int EventToken { get; set; }

        /// <summary>
        /// Achievement points.
        /// </summary>
        /// <value>Achievement points.</value>
        [DataMember(Name = "achievements_points", IsRequired = true, EmitDefaultValue = true)]
        public int AchievementsPoints { get; set; }

        /// <summary>
        /// Banned.
        /// </summary>
        /// <value>Banned.</value>
        [DataMember(Name = "banned", IsRequired = true, EmitDefaultValue = true)]
        public bool Banned { get; set; }

        /// <summary>
        /// Ban reason.
        /// </summary>
        /// <value>Ban reason.</value>
        [DataMember(Name = "ban_reason", EmitDefaultValue = false)]
        public string BanReason { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MyAccountDetails {\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Member: ").Append(Member).Append("\n");
            sb.Append("  MemberExpiration: ").Append(MemberExpiration).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Badges: ").Append(Badges).Append("\n");
            sb.Append("  Skins: ").Append(Skins).Append("\n");
            sb.Append("  Gems: ").Append(Gems).Append("\n");
            sb.Append("  EventToken: ").Append(EventToken).Append("\n");
            sb.Append("  AchievementsPoints: ").Append(AchievementsPoints).Append("\n");
            sb.Append("  Banned: ").Append(Banned).Append("\n");
            sb.Append("  BanReason: ").Append(BanReason).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
