/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// PasswordResetConfirmSchema
    /// </summary>
    [DataContract(Name = "PasswordResetConfirmSchema")]
    public partial class PasswordResetConfirmSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PasswordResetConfirmSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PasswordResetConfirmSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="PasswordResetConfirmSchema" /> class.
        /// </summary>
        /// <param name="token">Password reset token. (required).</param>
        /// <param name="newPassword">Your new password. (required).</param>
        public PasswordResetConfirmSchema(string token = default, string newPassword = default)
        {
            // to ensure "token" is required (not null)
            if (token == null)
            {
                throw new ArgumentNullException("token is a required property for PasswordResetConfirmSchema and cannot be null");
            }
            this.Token = token;
            // to ensure "newPassword" is required (not null)
            if (newPassword == null)
            {
                throw new ArgumentNullException("newPassword is a required property for PasswordResetConfirmSchema and cannot be null");
            }
            this.NewPassword = newPassword;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Password reset token.
        /// </summary>
        /// <value>Password reset token.</value>
        [DataMember(Name = "token", IsRequired = true, EmitDefaultValue = true)]
        public string Token { get; set; }

        /// <summary>
        /// Your new password.
        /// </summary>
        /// <value>Your new password.</value>
        [DataMember(Name = "new_password", IsRequired = true, EmitDefaultValue = true)]
        public string NewPassword { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PasswordResetConfirmSchema {\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  NewPassword: ").Append(NewPassword).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // NewPassword (string) maxLength
            if (this.NewPassword != null && this.NewPassword.Length > 50)
            {
                yield return new ValidationResult("Invalid value for NewPassword, length must be less than 50.", new [] { "NewPassword" });
            }

            // NewPassword (string) minLength
            if (this.NewPassword != null && this.NewPassword.Length < 5)
            {
                yield return new ValidationResult("Invalid value for NewPassword, length must be greater than 5.", new [] { "NewPassword" });
            }

            if (this.NewPassword != null) {
                // NewPassword (string) pattern
                Regex regexNewPassword = new Regex(@"^[^\s]+$", RegexOptions.CultureInvariant);
                if (!regexNewPassword.Match(this.NewPassword).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for NewPassword, must match a pattern of " + regexNewPassword, new [] { "NewPassword" });
                }
            }

            yield break;
        }
    }

}
