/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// RewardDataSchema
    /// </summary>
    [DataContract(Name = "RewardDataSchema")]
    public partial class RewardDataSchema : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RewardDataSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RewardDataSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="RewardDataSchema" /> class.
        /// </summary>
        /// <param name="cooldown">Cooldown details. (required).</param>
        /// <param name="rewards">Reward details. (required).</param>
        /// <param name="character">Player details. (required).</param>
        public RewardDataSchema(CooldownSchema cooldown = default, RewardsSchema rewards = default, CharacterSchema character = default)
        {
            // to ensure "cooldown" is required (not null)
            if (cooldown == null)
            {
                throw new ArgumentNullException("cooldown is a required property for RewardDataSchema and cannot be null");
            }
            this.Cooldown = cooldown;
            // to ensure "rewards" is required (not null)
            if (rewards == null)
            {
                throw new ArgumentNullException("rewards is a required property for RewardDataSchema and cannot be null");
            }
            this.Rewards = rewards;
            // to ensure "character" is required (not null)
            if (character == null)
            {
                throw new ArgumentNullException("character is a required property for RewardDataSchema and cannot be null");
            }
            this.Character = character;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Cooldown details.
        /// </summary>
        /// <value>Cooldown details.</value>
        [DataMember(Name = "cooldown", IsRequired = true, EmitDefaultValue = true)]
        public CooldownSchema Cooldown { get; set; }

        /// <summary>
        /// Reward details.
        /// </summary>
        /// <value>Reward details.</value>
        [DataMember(Name = "rewards", IsRequired = true, EmitDefaultValue = true)]
        public RewardsSchema Rewards { get; set; }

        /// <summary>
        /// Player details.
        /// </summary>
        /// <value>Player details.</value>
        [DataMember(Name = "character", IsRequired = true, EmitDefaultValue = true)]
        public CharacterSchema Character { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RewardDataSchema {\n");
            sb.Append("  Cooldown: ").Append(Cooldown).Append("\n");
            sb.Append("  Rewards: ").Append(Rewards).Append("\n");
            sb.Append("  Character: ").Append(Character).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
