/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// TaskSchema
    /// </summary>
    [DataContract(Name = "TaskSchema")]
    public partial class TaskSchema : IValidatableObject
    {

        /// <summary>
        /// The type of task.
        /// </summary>
        /// <value>The type of task.</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TaskType Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TaskSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskSchema" /> class.
        /// </summary>
        /// <param name="code">Task objective. (required).</param>
        /// <param name="type">The type of task. (required).</param>
        /// <param name="total">The total required to complete the task. (required).</param>
        /// <param name="rewards">Rewards for completing the task. (required).</param>
        public TaskSchema(string code = default, TaskType type = default, int total = default, RewardsSchema rewards = default)
        {
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new ArgumentNullException("code is a required property for TaskSchema and cannot be null");
            }
            this.Code = code;
            this.Type = type;
            this.Total = total;
            // to ensure "rewards" is required (not null)
            if (rewards == null)
            {
                throw new ArgumentNullException("rewards is a required property for TaskSchema and cannot be null");
            }
            this.Rewards = rewards;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Task objective.
        /// </summary>
        /// <value>Task objective.</value>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public string Code { get; set; }

        /// <summary>
        /// The total required to complete the task.
        /// </summary>
        /// <value>The total required to complete the task.</value>
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public int Total { get; set; }

        /// <summary>
        /// Rewards for completing the task.
        /// </summary>
        /// <value>Rewards for completing the task.</value>
        [DataMember(Name = "rewards", IsRequired = true, EmitDefaultValue = true)]
        public RewardsSchema Rewards { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TaskSchema {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Rewards: ").Append(Rewards).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
