/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// TransitionSchema
    /// </summary>
    [DataContract(Name = "TransitionSchema")]
    public partial class TransitionSchema : IValidatableObject
    {

        /// <summary>
        /// Layer of the destination.
        /// </summary>
        /// <value>Layer of the destination.</value>
        [DataMember(Name = "layer", IsRequired = true, EmitDefaultValue = true)]
        public MapLayer Layer { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransitionSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransitionSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransitionSchema" /> class.
        /// </summary>
        /// <param name="mapId">ID of the destination map. (required).</param>
        /// <param name="x">Position X of the destination. (required).</param>
        /// <param name="y">Position Y of the destination. (required).</param>
        /// <param name="layer">Layer of the destination. (required).</param>
        /// <param name="conditions">Conditions for the transition..</param>
        public TransitionSchema(int mapId = default, int x = default, int y = default, MapLayer layer = default, List<ConditionSchema> conditions = default)
        {
            this.MapId = mapId;
            this.X = x;
            this.Y = y;
            this.Layer = layer;
            this.Conditions = conditions;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// ID of the destination map.
        /// </summary>
        /// <value>ID of the destination map.</value>
        [DataMember(Name = "map_id", IsRequired = true, EmitDefaultValue = true)]
        public int MapId { get; set; }

        /// <summary>
        /// Position X of the destination.
        /// </summary>
        /// <value>Position X of the destination.</value>
        [DataMember(Name = "x", IsRequired = true, EmitDefaultValue = true)]
        public int X { get; set; }

        /// <summary>
        /// Position Y of the destination.
        /// </summary>
        /// <value>Position Y of the destination.</value>
        [DataMember(Name = "y", IsRequired = true, EmitDefaultValue = true)]
        public int Y { get; set; }

        /// <summary>
        /// Conditions for the transition.
        /// </summary>
        /// <value>Conditions for the transition.</value>
        [DataMember(Name = "conditions", EmitDefaultValue = false)]
        public List<ConditionSchema> Conditions { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransitionSchema {\n");
            sb.Append("  MapId: ").Append(MapId).Append("\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Layer: ").Append(Layer).Append("\n");
            sb.Append("  Conditions: ").Append(Conditions).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
