/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ArtifactsMmoClient.Client.FileParameter;
using OpenAPIDateConverter = ArtifactsMmoClient.Client.OpenAPIDateConverter;

namespace ArtifactsMmoClient.Model
{
    /// <summary>
    /// UnequipSchema
    /// </summary>
    [DataContract(Name = "UnequipSchema")]
    public partial class UnequipSchema : IValidatableObject
    {

        /// <summary>
        /// Item slot.
        /// </summary>
        /// <value>Item slot.</value>
        [DataMember(Name = "slot", IsRequired = true, EmitDefaultValue = true)]
        public ItemSlot Slot { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="UnequipSchema" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UnequipSchema()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="UnequipSchema" /> class.
        /// </summary>
        /// <param name="slot">Item slot. (required).</param>
        /// <param name="quantity">Item quantity. Applicable to utilities only. (default to 1).</param>
        public UnequipSchema(ItemSlot slot = default, int quantity = 1)
        {
            this.Slot = slot;
            this.Quantity = quantity;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Item quantity. Applicable to utilities only.
        /// </summary>
        /// <value>Item quantity. Applicable to utilities only.</value>
        [DataMember(Name = "quantity", EmitDefaultValue = false)]
        public int Quantity { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UnequipSchema {\n");
            sb.Append("  Slot: ").Append(Slot).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Quantity (int) maximum
            if (this.Quantity > (int)100)
            {
                yield return new ValidationResult("Invalid value for Quantity, must be a value less than or equal to 100.", new [] { "Quantity" });
            }

            // Quantity (int) minimum
            if (this.Quantity < (int)1)
            {
                yield return new ValidationResult("Invalid value for Quantity, must be a value greater than or equal to 1.", new [] { "Quantity" });
            }

            yield break;
        }
    }

}
