/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using ArtifactsMmoClient.Client;
using ArtifactsMmoClient.Model;

namespace ArtifactsMmoClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILeaderboardApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Accounts Leaderboard
        /// </summary>
        /// <remarks>
        /// Fetch leaderboard details.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of account leaderboards. (optional)</param>
        /// <param name="name">Account name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <returns>DataPageAccountLeaderboardSchema</returns>
        DataPageAccountLeaderboardSchema GetAccountsLeaderboardLeaderboardAccountsGet(AccountLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default);

        /// <summary>
        /// Get Accounts Leaderboard
        /// </summary>
        /// <remarks>
        /// Fetch leaderboard details.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of account leaderboards. (optional)</param>
        /// <param name="name">Account name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <returns>ApiResponse of DataPageAccountLeaderboardSchema</returns>
        ApiResponse<DataPageAccountLeaderboardSchema> GetAccountsLeaderboardLeaderboardAccountsGetWithHttpInfo(AccountLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default);
        /// <summary>
        /// Get Characters Leaderboard
        /// </summary>
        /// <remarks>
        /// Fetch leaderboard details.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of character leaderboards. (optional)</param>
        /// <param name="name">Character name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <returns>DataPageCharacterLeaderboardSchema</returns>
        DataPageCharacterLeaderboardSchema GetCharactersLeaderboardLeaderboardCharactersGet(CharacterLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default);

        /// <summary>
        /// Get Characters Leaderboard
        /// </summary>
        /// <remarks>
        /// Fetch leaderboard details.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of character leaderboards. (optional)</param>
        /// <param name="name">Character name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <returns>ApiResponse of DataPageCharacterLeaderboardSchema</returns>
        ApiResponse<DataPageCharacterLeaderboardSchema> GetCharactersLeaderboardLeaderboardCharactersGetWithHttpInfo(CharacterLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILeaderboardApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get Accounts Leaderboard
        /// </summary>
        /// <remarks>
        /// Fetch leaderboard details.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of account leaderboards. (optional)</param>
        /// <param name="name">Account name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataPageAccountLeaderboardSchema</returns>
        System.Threading.Tasks.Task<DataPageAccountLeaderboardSchema> GetAccountsLeaderboardLeaderboardAccountsGetAsync(AccountLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Accounts Leaderboard
        /// </summary>
        /// <remarks>
        /// Fetch leaderboard details.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of account leaderboards. (optional)</param>
        /// <param name="name">Account name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataPageAccountLeaderboardSchema)</returns>
        System.Threading.Tasks.Task<ApiResponse<DataPageAccountLeaderboardSchema>> GetAccountsLeaderboardLeaderboardAccountsGetWithHttpInfoAsync(AccountLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Characters Leaderboard
        /// </summary>
        /// <remarks>
        /// Fetch leaderboard details.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of character leaderboards. (optional)</param>
        /// <param name="name">Character name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataPageCharacterLeaderboardSchema</returns>
        System.Threading.Tasks.Task<DataPageCharacterLeaderboardSchema> GetCharactersLeaderboardLeaderboardCharactersGetAsync(CharacterLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Characters Leaderboard
        /// </summary>
        /// <remarks>
        /// Fetch leaderboard details.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of character leaderboards. (optional)</param>
        /// <param name="name">Character name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataPageCharacterLeaderboardSchema)</returns>
        System.Threading.Tasks.Task<ApiResponse<DataPageCharacterLeaderboardSchema>> GetCharactersLeaderboardLeaderboardCharactersGetWithHttpInfoAsync(CharacterLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILeaderboardApi : ILeaderboardApiSync, ILeaderboardApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class LeaderboardApi : IDisposable, ILeaderboardApi
    {
        private ArtifactsMmoClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LeaderboardApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public LeaderboardApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LeaderboardApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public LeaderboardApi(string basePath)
        {
            this.Configuration = ArtifactsMmoClient.Client.Configuration.MergeConfigurations(
                ArtifactsMmoClient.Client.GlobalConfiguration.Instance,
                new ArtifactsMmoClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new ArtifactsMmoClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = ArtifactsMmoClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LeaderboardApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public LeaderboardApi(ArtifactsMmoClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = ArtifactsMmoClient.Client.Configuration.MergeConfigurations(
                ArtifactsMmoClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new ArtifactsMmoClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = ArtifactsMmoClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LeaderboardApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public LeaderboardApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LeaderboardApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public LeaderboardApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = ArtifactsMmoClient.Client.Configuration.MergeConfigurations(
                ArtifactsMmoClient.Client.GlobalConfiguration.Instance,
                new ArtifactsMmoClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new ArtifactsMmoClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = ArtifactsMmoClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LeaderboardApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public LeaderboardApi(HttpClient client, ArtifactsMmoClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = ArtifactsMmoClient.Client.Configuration.MergeConfigurations(
                ArtifactsMmoClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new ArtifactsMmoClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = ArtifactsMmoClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LeaderboardApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public LeaderboardApi(ArtifactsMmoClient.Client.ISynchronousClient client, ArtifactsMmoClient.Client.IAsynchronousClient asyncClient, ArtifactsMmoClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = ArtifactsMmoClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public ArtifactsMmoClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public ArtifactsMmoClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public ArtifactsMmoClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ArtifactsMmoClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ArtifactsMmoClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get Accounts Leaderboard Fetch leaderboard details.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of account leaderboards. (optional)</param>
        /// <param name="name">Account name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <returns>DataPageAccountLeaderboardSchema</returns>
        public DataPageAccountLeaderboardSchema GetAccountsLeaderboardLeaderboardAccountsGet(AccountLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default)
        {
            ArtifactsMmoClient.Client.ApiResponse<DataPageAccountLeaderboardSchema> localVarResponse = GetAccountsLeaderboardLeaderboardAccountsGetWithHttpInfo(sort, name, page, size);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Accounts Leaderboard Fetch leaderboard details.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of account leaderboards. (optional)</param>
        /// <param name="name">Account name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <returns>ApiResponse of DataPageAccountLeaderboardSchema</returns>
        public ArtifactsMmoClient.Client.ApiResponse<DataPageAccountLeaderboardSchema> GetAccountsLeaderboardLeaderboardAccountsGetWithHttpInfo(AccountLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default)
        {
            ArtifactsMmoClient.Client.RequestOptions localVarRequestOptions = new ArtifactsMmoClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }
            if (name != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "name", name));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (size != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "size", size));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<DataPageAccountLeaderboardSchema>("/leaderboard/accounts", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAccountsLeaderboardLeaderboardAccountsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Accounts Leaderboard Fetch leaderboard details.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of account leaderboards. (optional)</param>
        /// <param name="name">Account name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataPageAccountLeaderboardSchema</returns>
        public async System.Threading.Tasks.Task<DataPageAccountLeaderboardSchema> GetAccountsLeaderboardLeaderboardAccountsGetAsync(AccountLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default, System.Threading.CancellationToken cancellationToken = default)
        {
            ArtifactsMmoClient.Client.ApiResponse<DataPageAccountLeaderboardSchema> localVarResponse = await GetAccountsLeaderboardLeaderboardAccountsGetWithHttpInfoAsync(sort, name, page, size, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Accounts Leaderboard Fetch leaderboard details.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of account leaderboards. (optional)</param>
        /// <param name="name">Account name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataPageAccountLeaderboardSchema)</returns>
        public async System.Threading.Tasks.Task<ArtifactsMmoClient.Client.ApiResponse<DataPageAccountLeaderboardSchema>> GetAccountsLeaderboardLeaderboardAccountsGetWithHttpInfoAsync(AccountLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default, System.Threading.CancellationToken cancellationToken = default)
        {

            ArtifactsMmoClient.Client.RequestOptions localVarRequestOptions = new ArtifactsMmoClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }
            if (name != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "name", name));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (size != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "size", size));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<DataPageAccountLeaderboardSchema>("/leaderboard/accounts", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAccountsLeaderboardLeaderboardAccountsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Characters Leaderboard Fetch leaderboard details.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of character leaderboards. (optional)</param>
        /// <param name="name">Character name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <returns>DataPageCharacterLeaderboardSchema</returns>
        public DataPageCharacterLeaderboardSchema GetCharactersLeaderboardLeaderboardCharactersGet(CharacterLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default)
        {
            ArtifactsMmoClient.Client.ApiResponse<DataPageCharacterLeaderboardSchema> localVarResponse = GetCharactersLeaderboardLeaderboardCharactersGetWithHttpInfo(sort, name, page, size);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Characters Leaderboard Fetch leaderboard details.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of character leaderboards. (optional)</param>
        /// <param name="name">Character name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <returns>ApiResponse of DataPageCharacterLeaderboardSchema</returns>
        public ArtifactsMmoClient.Client.ApiResponse<DataPageCharacterLeaderboardSchema> GetCharactersLeaderboardLeaderboardCharactersGetWithHttpInfo(CharacterLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default)
        {
            ArtifactsMmoClient.Client.RequestOptions localVarRequestOptions = new ArtifactsMmoClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }
            if (name != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "name", name));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (size != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "size", size));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<DataPageCharacterLeaderboardSchema>("/leaderboard/characters", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCharactersLeaderboardLeaderboardCharactersGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Characters Leaderboard Fetch leaderboard details.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of character leaderboards. (optional)</param>
        /// <param name="name">Character name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataPageCharacterLeaderboardSchema</returns>
        public async System.Threading.Tasks.Task<DataPageCharacterLeaderboardSchema> GetCharactersLeaderboardLeaderboardCharactersGetAsync(CharacterLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default, System.Threading.CancellationToken cancellationToken = default)
        {
            ArtifactsMmoClient.Client.ApiResponse<DataPageCharacterLeaderboardSchema> localVarResponse = await GetCharactersLeaderboardLeaderboardCharactersGetWithHttpInfoAsync(sort, name, page, size, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Characters Leaderboard Fetch leaderboard details.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sort">Sort of character leaderboards. (optional)</param>
        /// <param name="name">Character name. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataPageCharacterLeaderboardSchema)</returns>
        public async System.Threading.Tasks.Task<ArtifactsMmoClient.Client.ApiResponse<DataPageCharacterLeaderboardSchema>> GetCharactersLeaderboardLeaderboardCharactersGetWithHttpInfoAsync(CharacterLeaderboardType? sort = default, string? name = default, int? page = default, int? size = default, System.Threading.CancellationToken cancellationToken = default)
        {

            ArtifactsMmoClient.Client.RequestOptions localVarRequestOptions = new ArtifactsMmoClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }
            if (name != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "name", name));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (size != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "size", size));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<DataPageCharacterLeaderboardSchema>("/leaderboard/characters", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCharactersLeaderboardLeaderboardCharactersGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
