/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using ArtifactsMmoClient.Client;
using ArtifactsMmoClient.Model;

namespace ArtifactsMmoClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMonstersApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get All Monsters
        /// </summary>
        /// <remarks>
        /// Fetch monsters details.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Name of the monster. (optional)</param>
        /// <param name="minLevel">Minimum level. (optional)</param>
        /// <param name="maxLevel">Maximum level. (optional)</param>
        /// <param name="drop">Item code of the drop. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <returns>DataPageMonsterSchema</returns>
        DataPageMonsterSchema GetAllMonstersMonstersGet(string? name = default, int? minLevel = default, int? maxLevel = default, string? drop = default, int? page = default, int? size = default);

        /// <summary>
        /// Get All Monsters
        /// </summary>
        /// <remarks>
        /// Fetch monsters details.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Name of the monster. (optional)</param>
        /// <param name="minLevel">Minimum level. (optional)</param>
        /// <param name="maxLevel">Maximum level. (optional)</param>
        /// <param name="drop">Item code of the drop. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <returns>ApiResponse of DataPageMonsterSchema</returns>
        ApiResponse<DataPageMonsterSchema> GetAllMonstersMonstersGetWithHttpInfo(string? name = default, int? minLevel = default, int? maxLevel = default, string? drop = default, int? page = default, int? size = default);
        /// <summary>
        /// Get Monster
        /// </summary>
        /// <remarks>
        /// Retrieve the details of a monster.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">The code of the monster.</param>
        /// <returns>MonsterResponseSchema</returns>
        MonsterResponseSchema GetMonsterMonstersCodeGet(string code);

        /// <summary>
        /// Get Monster
        /// </summary>
        /// <remarks>
        /// Retrieve the details of a monster.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">The code of the monster.</param>
        /// <returns>ApiResponse of MonsterResponseSchema</returns>
        ApiResponse<MonsterResponseSchema> GetMonsterMonstersCodeGetWithHttpInfo(string code);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMonstersApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get All Monsters
        /// </summary>
        /// <remarks>
        /// Fetch monsters details.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Name of the monster. (optional)</param>
        /// <param name="minLevel">Minimum level. (optional)</param>
        /// <param name="maxLevel">Maximum level. (optional)</param>
        /// <param name="drop">Item code of the drop. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataPageMonsterSchema</returns>
        System.Threading.Tasks.Task<DataPageMonsterSchema> GetAllMonstersMonstersGetAsync(string? name = default, int? minLevel = default, int? maxLevel = default, string? drop = default, int? page = default, int? size = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get All Monsters
        /// </summary>
        /// <remarks>
        /// Fetch monsters details.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Name of the monster. (optional)</param>
        /// <param name="minLevel">Minimum level. (optional)</param>
        /// <param name="maxLevel">Maximum level. (optional)</param>
        /// <param name="drop">Item code of the drop. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataPageMonsterSchema)</returns>
        System.Threading.Tasks.Task<ApiResponse<DataPageMonsterSchema>> GetAllMonstersMonstersGetWithHttpInfoAsync(string? name = default, int? minLevel = default, int? maxLevel = default, string? drop = default, int? page = default, int? size = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Monster
        /// </summary>
        /// <remarks>
        /// Retrieve the details of a monster.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">The code of the monster.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MonsterResponseSchema</returns>
        System.Threading.Tasks.Task<MonsterResponseSchema> GetMonsterMonstersCodeGetAsync(string code, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Monster
        /// </summary>
        /// <remarks>
        /// Retrieve the details of a monster.
        /// </remarks>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">The code of the monster.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MonsterResponseSchema)</returns>
        System.Threading.Tasks.Task<ApiResponse<MonsterResponseSchema>> GetMonsterMonstersCodeGetWithHttpInfoAsync(string code, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMonstersApi : IMonstersApiSync, IMonstersApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MonstersApi : IDisposable, IMonstersApi
    {
        private ArtifactsMmoClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MonstersApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public MonstersApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MonstersApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public MonstersApi(string basePath)
        {
            this.Configuration = ArtifactsMmoClient.Client.Configuration.MergeConfigurations(
                ArtifactsMmoClient.Client.GlobalConfiguration.Instance,
                new ArtifactsMmoClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new ArtifactsMmoClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = ArtifactsMmoClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MonstersApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public MonstersApi(ArtifactsMmoClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = ArtifactsMmoClient.Client.Configuration.MergeConfigurations(
                ArtifactsMmoClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new ArtifactsMmoClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = ArtifactsMmoClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MonstersApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MonstersApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MonstersApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MonstersApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = ArtifactsMmoClient.Client.Configuration.MergeConfigurations(
                ArtifactsMmoClient.Client.GlobalConfiguration.Instance,
                new ArtifactsMmoClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new ArtifactsMmoClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = ArtifactsMmoClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MonstersApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MonstersApi(HttpClient client, ArtifactsMmoClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = ArtifactsMmoClient.Client.Configuration.MergeConfigurations(
                ArtifactsMmoClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new ArtifactsMmoClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = ArtifactsMmoClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MonstersApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public MonstersApi(ArtifactsMmoClient.Client.ISynchronousClient client, ArtifactsMmoClient.Client.IAsynchronousClient asyncClient, ArtifactsMmoClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = ArtifactsMmoClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public ArtifactsMmoClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public ArtifactsMmoClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public ArtifactsMmoClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ArtifactsMmoClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ArtifactsMmoClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get All Monsters Fetch monsters details.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Name of the monster. (optional)</param>
        /// <param name="minLevel">Minimum level. (optional)</param>
        /// <param name="maxLevel">Maximum level. (optional)</param>
        /// <param name="drop">Item code of the drop. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <returns>DataPageMonsterSchema</returns>
        public DataPageMonsterSchema GetAllMonstersMonstersGet(string? name = default, int? minLevel = default, int? maxLevel = default, string? drop = default, int? page = default, int? size = default)
        {
            ArtifactsMmoClient.Client.ApiResponse<DataPageMonsterSchema> localVarResponse = GetAllMonstersMonstersGetWithHttpInfo(name, minLevel, maxLevel, drop, page, size);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get All Monsters Fetch monsters details.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Name of the monster. (optional)</param>
        /// <param name="minLevel">Minimum level. (optional)</param>
        /// <param name="maxLevel">Maximum level. (optional)</param>
        /// <param name="drop">Item code of the drop. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <returns>ApiResponse of DataPageMonsterSchema</returns>
        public ArtifactsMmoClient.Client.ApiResponse<DataPageMonsterSchema> GetAllMonstersMonstersGetWithHttpInfo(string? name = default, int? minLevel = default, int? maxLevel = default, string? drop = default, int? page = default, int? size = default)
        {
            ArtifactsMmoClient.Client.RequestOptions localVarRequestOptions = new ArtifactsMmoClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (name != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "name", name));
            }
            if (minLevel != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "min_level", minLevel));
            }
            if (maxLevel != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "max_level", maxLevel));
            }
            if (drop != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "drop", drop));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (size != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "size", size));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<DataPageMonsterSchema>("/monsters", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllMonstersMonstersGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get All Monsters Fetch monsters details.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Name of the monster. (optional)</param>
        /// <param name="minLevel">Minimum level. (optional)</param>
        /// <param name="maxLevel">Maximum level. (optional)</param>
        /// <param name="drop">Item code of the drop. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataPageMonsterSchema</returns>
        public async System.Threading.Tasks.Task<DataPageMonsterSchema> GetAllMonstersMonstersGetAsync(string? name = default, int? minLevel = default, int? maxLevel = default, string? drop = default, int? page = default, int? size = default, System.Threading.CancellationToken cancellationToken = default)
        {
            ArtifactsMmoClient.Client.ApiResponse<DataPageMonsterSchema> localVarResponse = await GetAllMonstersMonstersGetWithHttpInfoAsync(name, minLevel, maxLevel, drop, page, size, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get All Monsters Fetch monsters details.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Name of the monster. (optional)</param>
        /// <param name="minLevel">Minimum level. (optional)</param>
        /// <param name="maxLevel">Maximum level. (optional)</param>
        /// <param name="drop">Item code of the drop. (optional)</param>
        /// <param name="page">Page number (optional, default to 1)</param>
        /// <param name="size">Page size (optional, default to 50)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataPageMonsterSchema)</returns>
        public async System.Threading.Tasks.Task<ArtifactsMmoClient.Client.ApiResponse<DataPageMonsterSchema>> GetAllMonstersMonstersGetWithHttpInfoAsync(string? name = default, int? minLevel = default, int? maxLevel = default, string? drop = default, int? page = default, int? size = default, System.Threading.CancellationToken cancellationToken = default)
        {

            ArtifactsMmoClient.Client.RequestOptions localVarRequestOptions = new ArtifactsMmoClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (name != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "name", name));
            }
            if (minLevel != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "min_level", minLevel));
            }
            if (maxLevel != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "max_level", maxLevel));
            }
            if (drop != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "drop", drop));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (size != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtifactsMmoClient.Client.ClientUtils.ParameterToMultiMap("", "size", size));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<DataPageMonsterSchema>("/monsters", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllMonstersMonstersGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Monster Retrieve the details of a monster.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">The code of the monster.</param>
        /// <returns>MonsterResponseSchema</returns>
        public MonsterResponseSchema GetMonsterMonstersCodeGet(string code)
        {
            ArtifactsMmoClient.Client.ApiResponse<MonsterResponseSchema> localVarResponse = GetMonsterMonstersCodeGetWithHttpInfo(code);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Monster Retrieve the details of a monster.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">The code of the monster.</param>
        /// <returns>ApiResponse of MonsterResponseSchema</returns>
        public ArtifactsMmoClient.Client.ApiResponse<MonsterResponseSchema> GetMonsterMonstersCodeGetWithHttpInfo(string code)
        {
            // verify the required parameter 'code' is set
            if (code == null)
                throw new ArtifactsMmoClient.Client.ApiException(400, "Missing required parameter 'code' when calling MonstersApi->GetMonsterMonstersCodeGet");

            ArtifactsMmoClient.Client.RequestOptions localVarRequestOptions = new ArtifactsMmoClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("code", ArtifactsMmoClient.Client.ClientUtils.ParameterToString(code)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<MonsterResponseSchema>("/monsters/{code}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMonsterMonstersCodeGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Monster Retrieve the details of a monster.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">The code of the monster.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MonsterResponseSchema</returns>
        public async System.Threading.Tasks.Task<MonsterResponseSchema> GetMonsterMonstersCodeGetAsync(string code, System.Threading.CancellationToken cancellationToken = default)
        {
            ArtifactsMmoClient.Client.ApiResponse<MonsterResponseSchema> localVarResponse = await GetMonsterMonstersCodeGetWithHttpInfoAsync(code, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Monster Retrieve the details of a monster.
        /// </summary>
        /// <exception cref="ArtifactsMmoClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code">The code of the monster.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MonsterResponseSchema)</returns>
        public async System.Threading.Tasks.Task<ArtifactsMmoClient.Client.ApiResponse<MonsterResponseSchema>> GetMonsterMonstersCodeGetWithHttpInfoAsync(string code, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'code' is set
            if (code == null)
                throw new ArtifactsMmoClient.Client.ApiException(400, "Missing required parameter 'code' when calling MonstersApi->GetMonsterMonstersCodeGet");


            ArtifactsMmoClient.Client.RequestOptions localVarRequestOptions = new ArtifactsMmoClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = ArtifactsMmoClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("code", ArtifactsMmoClient.Client.ClientUtils.ParameterToString(code)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<MonsterResponseSchema>("/monsters/{code}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMonsterMonstersCodeGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
