/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ArtifactsMmoClient.Client;
using ArtifactsMmoClient.Api;
// uncomment below to import models
//using ArtifactsMmoClient.Model;

namespace ArtifactsMmoClient.Test.Api
{
    /// <summary>
    ///  Class for testing GrandExchangeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class GrandExchangeApiTests : IDisposable
    {
        private GrandExchangeApi instance;

        public GrandExchangeApiTests()
        {
            instance = new GrandExchangeApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GrandExchangeApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' GrandExchangeApi
            //Assert.IsType<GrandExchangeApi>(instance);
        }

        /// <summary>
        /// Test GetGeSellHistoryGrandexchangeHistoryCodeGet
        /// </summary>
        [Fact]
        public void GetGeSellHistoryGrandexchangeHistoryCodeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string code = null;
            //string? seller = null;
            //string? buyer = null;
            //int? page = null;
            //int? size = null;
            //var response = instance.GetGeSellHistoryGrandexchangeHistoryCodeGet(code, seller, buyer, page, size);
            //Assert.IsType<DataPageGeOrderHistorySchema>(response);
        }

        /// <summary>
        /// Test GetGeSellOrderGrandexchangeOrdersIdGet
        /// </summary>
        [Fact]
        public void GetGeSellOrderGrandexchangeOrdersIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetGeSellOrderGrandexchangeOrdersIdGet(id);
            //Assert.IsType<GEOrderResponseSchema>(response);
        }

        /// <summary>
        /// Test GetGeSellOrdersGrandexchangeOrdersGet
        /// </summary>
        [Fact]
        public void GetGeSellOrdersGrandexchangeOrdersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? code = null;
            //string? seller = null;
            //int? page = null;
            //int? size = null;
            //var response = instance.GetGeSellOrdersGrandexchangeOrdersGet(code, seller, page, size);
            //Assert.IsType<DataPageGEOrderSchema>(response);
        }
    }
}
