/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ArtifactsMmoClient.Client;
using ArtifactsMmoClient.Api;
// uncomment below to import models
//using ArtifactsMmoClient.Model;

namespace ArtifactsMmoClient.Test.Api
{
    /// <summary>
    ///  Class for testing ItemsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ItemsApiTests : IDisposable
    {
        private ItemsApi instance;

        public ItemsApiTests()
        {
            instance = new ItemsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ItemsApi
            //Assert.IsType<ItemsApi>(instance);
        }

        /// <summary>
        /// Test GetAllItemsItemsGet
        /// </summary>
        [Fact]
        public void GetAllItemsItemsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? name = null;
            //int? minLevel = null;
            //int? maxLevel = null;
            //ItemType? type = null;
            //CraftSkill? craftSkill = null;
            //string? craftMaterial = null;
            //int? page = null;
            //int? size = null;
            //var response = instance.GetAllItemsItemsGet(name, minLevel, maxLevel, type, craftSkill, craftMaterial, page, size);
            //Assert.IsType<DataPageItemSchema>(response);
        }

        /// <summary>
        /// Test GetItemItemsCodeGet
        /// </summary>
        [Fact]
        public void GetItemItemsCodeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string code = null;
            //var response = instance.GetItemItemsCodeGet(code);
            //Assert.IsType<ItemResponseSchema>(response);
        }
    }
}
