/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ArtifactsMmoClient.Client;
using ArtifactsMmoClient.Api;
// uncomment below to import models
//using ArtifactsMmoClient.Model;

namespace ArtifactsMmoClient.Test.Api
{
    /// <summary>
    ///  Class for testing LeaderboardApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LeaderboardApiTests : IDisposable
    {
        private LeaderboardApi instance;

        public LeaderboardApiTests()
        {
            instance = new LeaderboardApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LeaderboardApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LeaderboardApi
            //Assert.IsType<LeaderboardApi>(instance);
        }

        /// <summary>
        /// Test GetAccountsLeaderboardLeaderboardAccountsGet
        /// </summary>
        [Fact]
        public void GetAccountsLeaderboardLeaderboardAccountsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AccountLeaderboardType? sort = null;
            //string? name = null;
            //int? page = null;
            //int? size = null;
            //var response = instance.GetAccountsLeaderboardLeaderboardAccountsGet(sort, name, page, size);
            //Assert.IsType<DataPageAccountLeaderboardSchema>(response);
        }

        /// <summary>
        /// Test GetCharactersLeaderboardLeaderboardCharactersGet
        /// </summary>
        [Fact]
        public void GetCharactersLeaderboardLeaderboardCharactersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CharacterLeaderboardType? sort = null;
            //string? name = null;
            //int? page = null;
            //int? size = null;
            //var response = instance.GetCharactersLeaderboardLeaderboardCharactersGet(sort, name, page, size);
            //Assert.IsType<DataPageCharacterLeaderboardSchema>(response);
        }
    }
}
