/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ArtifactsMmoClient.Client;
using ArtifactsMmoClient.Api;
// uncomment below to import models
//using ArtifactsMmoClient.Model;

namespace ArtifactsMmoClient.Test.Api
{
    /// <summary>
    ///  Class for testing ServerDetailsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ServerDetailsApiTests : IDisposable
    {
        private ServerDetailsApi instance;

        public ServerDetailsApiTests()
        {
            instance = new ServerDetailsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServerDetailsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ServerDetailsApi
            //Assert.IsType<ServerDetailsApi>(instance);
        }

        /// <summary>
        /// Test GetServerDetailsGet
        /// </summary>
        [Fact]
        public void GetServerDetailsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetServerDetailsGet();
            //Assert.IsType<StatusResponseSchema>(response);
        }
    }
}
