/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArtifactsMmoClient.Model;
using ArtifactsMmoClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArtifactsMmoClient.Test.Model
{
    /// <summary>
    ///  Class for testing AccountStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountStatus
        //private AccountStatus instance;

        public AccountStatusTests()
        {
            // TODO uncomment below to create an instance of AccountStatus
            //instance = new AccountStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountStatus
        /// </summary>
        [Fact]
        public void AccountStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountStatus
            //Assert.IsType<AccountStatus>(instance);
        }
    }
}
