/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArtifactsMmoClient.Model;
using ArtifactsMmoClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArtifactsMmoClient.Test.Model
{
    /// <summary>
    ///  Class for testing AccountDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountDetails
        //private AccountDetails instance;

        public AccountDetailsTests()
        {
            // TODO uncomment below to create an instance of AccountDetails
            //instance = new AccountDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountDetails
        /// </summary>
        [Fact]
        public void AccountDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountDetails
            //Assert.IsType<AccountDetails>(instance);
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Member'
        /// </summary>
        [Fact]
        public void MemberTest()
        {
            // TODO unit test for the property 'Member'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Badges'
        /// </summary>
        [Fact]
        public void BadgesTest()
        {
            // TODO unit test for the property 'Badges'
        }

        /// <summary>
        /// Test the property 'Skins'
        /// </summary>
        [Fact]
        public void SkinsTest()
        {
            // TODO unit test for the property 'Skins'
        }

        /// <summary>
        /// Test the property 'AchievementsPoints'
        /// </summary>
        [Fact]
        public void AchievementsPointsTest()
        {
            // TODO unit test for the property 'AchievementsPoints'
        }

        /// <summary>
        /// Test the property 'Banned'
        /// </summary>
        [Fact]
        public void BannedTest()
        {
            // TODO unit test for the property 'Banned'
        }

        /// <summary>
        /// Test the property 'BanReason'
        /// </summary>
        [Fact]
        public void BanReasonTest()
        {
            // TODO unit test for the property 'BanReason'
        }
    }
}
