/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArtifactsMmoClient.Model;
using ArtifactsMmoClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArtifactsMmoClient.Test.Model
{
    /// <summary>
    ///  Class for testing AchievementSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AchievementSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AchievementSchema
        //private AchievementSchema instance;

        public AchievementSchemaTests()
        {
            // TODO uncomment below to create an instance of AchievementSchema
            //instance = new AchievementSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AchievementSchema
        /// </summary>
        [Fact]
        public void AchievementSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" AchievementSchema
            //Assert.IsType<AchievementSchema>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Points'
        /// </summary>
        [Fact]
        public void PointsTest()
        {
            // TODO unit test for the property 'Points'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'Rewards'
        /// </summary>
        [Fact]
        public void RewardsTest()
        {
            // TODO unit test for the property 'Rewards'
        }
    }
}
