/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArtifactsMmoClient.Model;
using ArtifactsMmoClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArtifactsMmoClient.Test.Model
{
    /// <summary>
    ///  Class for testing AddAccountSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddAccountSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddAccountSchema
        //private AddAccountSchema instance;

        public AddAccountSchemaTests()
        {
            // TODO uncomment below to create an instance of AddAccountSchema
            //instance = new AddAccountSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddAccountSchema
        /// </summary>
        [Fact]
        public void AddAccountSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddAccountSchema
            //Assert.IsType<AddAccountSchema>(instance);
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
    }
}
