/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArtifactsMmoClient.Model;
using ArtifactsMmoClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArtifactsMmoClient.Test.Model
{
    /// <summary>
    ///  Class for testing BankItemTransactionSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BankItemTransactionSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BankItemTransactionSchema
        //private BankItemTransactionSchema instance;

        public BankItemTransactionSchemaTests()
        {
            // TODO uncomment below to create an instance of BankItemTransactionSchema
            //instance = new BankItemTransactionSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BankItemTransactionSchema
        /// </summary>
        [Fact]
        public void BankItemTransactionSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" BankItemTransactionSchema
            //Assert.IsType<BankItemTransactionSchema>(instance);
        }

        /// <summary>
        /// Test the property 'Cooldown'
        /// </summary>
        [Fact]
        public void CooldownTest()
        {
            // TODO unit test for the property 'Cooldown'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'Bank'
        /// </summary>
        [Fact]
        public void BankTest()
        {
            // TODO unit test for the property 'Bank'
        }

        /// <summary>
        /// Test the property 'Character'
        /// </summary>
        [Fact]
        public void CharacterTest()
        {
            // TODO unit test for the property 'Character'
        }
    }
}
