/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArtifactsMmoClient.Model;
using ArtifactsMmoClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArtifactsMmoClient.Test.Model
{
    /// <summary>
    ///  Class for testing CharacterSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CharacterSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CharacterSchema
        //private CharacterSchema instance;

        public CharacterSchemaTests()
        {
            // TODO uncomment below to create an instance of CharacterSchema
            //instance = new CharacterSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CharacterSchema
        /// </summary>
        [Fact]
        public void CharacterSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" CharacterSchema
            //Assert.IsType<CharacterSchema>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }

        /// <summary>
        /// Test the property 'Skin'
        /// </summary>
        [Fact]
        public void SkinTest()
        {
            // TODO unit test for the property 'Skin'
        }

        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Fact]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }

        /// <summary>
        /// Test the property 'Xp'
        /// </summary>
        [Fact]
        public void XpTest()
        {
            // TODO unit test for the property 'Xp'
        }

        /// <summary>
        /// Test the property 'MaxXp'
        /// </summary>
        [Fact]
        public void MaxXpTest()
        {
            // TODO unit test for the property 'MaxXp'
        }

        /// <summary>
        /// Test the property 'Gold'
        /// </summary>
        [Fact]
        public void GoldTest()
        {
            // TODO unit test for the property 'Gold'
        }

        /// <summary>
        /// Test the property 'Speed'
        /// </summary>
        [Fact]
        public void SpeedTest()
        {
            // TODO unit test for the property 'Speed'
        }

        /// <summary>
        /// Test the property 'MiningLevel'
        /// </summary>
        [Fact]
        public void MiningLevelTest()
        {
            // TODO unit test for the property 'MiningLevel'
        }

        /// <summary>
        /// Test the property 'MiningXp'
        /// </summary>
        [Fact]
        public void MiningXpTest()
        {
            // TODO unit test for the property 'MiningXp'
        }

        /// <summary>
        /// Test the property 'MiningMaxXp'
        /// </summary>
        [Fact]
        public void MiningMaxXpTest()
        {
            // TODO unit test for the property 'MiningMaxXp'
        }

        /// <summary>
        /// Test the property 'WoodcuttingLevel'
        /// </summary>
        [Fact]
        public void WoodcuttingLevelTest()
        {
            // TODO unit test for the property 'WoodcuttingLevel'
        }

        /// <summary>
        /// Test the property 'WoodcuttingXp'
        /// </summary>
        [Fact]
        public void WoodcuttingXpTest()
        {
            // TODO unit test for the property 'WoodcuttingXp'
        }

        /// <summary>
        /// Test the property 'WoodcuttingMaxXp'
        /// </summary>
        [Fact]
        public void WoodcuttingMaxXpTest()
        {
            // TODO unit test for the property 'WoodcuttingMaxXp'
        }

        /// <summary>
        /// Test the property 'FishingLevel'
        /// </summary>
        [Fact]
        public void FishingLevelTest()
        {
            // TODO unit test for the property 'FishingLevel'
        }

        /// <summary>
        /// Test the property 'FishingXp'
        /// </summary>
        [Fact]
        public void FishingXpTest()
        {
            // TODO unit test for the property 'FishingXp'
        }

        /// <summary>
        /// Test the property 'FishingMaxXp'
        /// </summary>
        [Fact]
        public void FishingMaxXpTest()
        {
            // TODO unit test for the property 'FishingMaxXp'
        }

        /// <summary>
        /// Test the property 'WeaponcraftingLevel'
        /// </summary>
        [Fact]
        public void WeaponcraftingLevelTest()
        {
            // TODO unit test for the property 'WeaponcraftingLevel'
        }

        /// <summary>
        /// Test the property 'WeaponcraftingXp'
        /// </summary>
        [Fact]
        public void WeaponcraftingXpTest()
        {
            // TODO unit test for the property 'WeaponcraftingXp'
        }

        /// <summary>
        /// Test the property 'WeaponcraftingMaxXp'
        /// </summary>
        [Fact]
        public void WeaponcraftingMaxXpTest()
        {
            // TODO unit test for the property 'WeaponcraftingMaxXp'
        }

        /// <summary>
        /// Test the property 'GearcraftingLevel'
        /// </summary>
        [Fact]
        public void GearcraftingLevelTest()
        {
            // TODO unit test for the property 'GearcraftingLevel'
        }

        /// <summary>
        /// Test the property 'GearcraftingXp'
        /// </summary>
        [Fact]
        public void GearcraftingXpTest()
        {
            // TODO unit test for the property 'GearcraftingXp'
        }

        /// <summary>
        /// Test the property 'GearcraftingMaxXp'
        /// </summary>
        [Fact]
        public void GearcraftingMaxXpTest()
        {
            // TODO unit test for the property 'GearcraftingMaxXp'
        }

        /// <summary>
        /// Test the property 'JewelrycraftingLevel'
        /// </summary>
        [Fact]
        public void JewelrycraftingLevelTest()
        {
            // TODO unit test for the property 'JewelrycraftingLevel'
        }

        /// <summary>
        /// Test the property 'JewelrycraftingXp'
        /// </summary>
        [Fact]
        public void JewelrycraftingXpTest()
        {
            // TODO unit test for the property 'JewelrycraftingXp'
        }

        /// <summary>
        /// Test the property 'JewelrycraftingMaxXp'
        /// </summary>
        [Fact]
        public void JewelrycraftingMaxXpTest()
        {
            // TODO unit test for the property 'JewelrycraftingMaxXp'
        }

        /// <summary>
        /// Test the property 'CookingLevel'
        /// </summary>
        [Fact]
        public void CookingLevelTest()
        {
            // TODO unit test for the property 'CookingLevel'
        }

        /// <summary>
        /// Test the property 'CookingXp'
        /// </summary>
        [Fact]
        public void CookingXpTest()
        {
            // TODO unit test for the property 'CookingXp'
        }

        /// <summary>
        /// Test the property 'CookingMaxXp'
        /// </summary>
        [Fact]
        public void CookingMaxXpTest()
        {
            // TODO unit test for the property 'CookingMaxXp'
        }

        /// <summary>
        /// Test the property 'AlchemyLevel'
        /// </summary>
        [Fact]
        public void AlchemyLevelTest()
        {
            // TODO unit test for the property 'AlchemyLevel'
        }

        /// <summary>
        /// Test the property 'AlchemyXp'
        /// </summary>
        [Fact]
        public void AlchemyXpTest()
        {
            // TODO unit test for the property 'AlchemyXp'
        }

        /// <summary>
        /// Test the property 'AlchemyMaxXp'
        /// </summary>
        [Fact]
        public void AlchemyMaxXpTest()
        {
            // TODO unit test for the property 'AlchemyMaxXp'
        }

        /// <summary>
        /// Test the property 'Hp'
        /// </summary>
        [Fact]
        public void HpTest()
        {
            // TODO unit test for the property 'Hp'
        }

        /// <summary>
        /// Test the property 'MaxHp'
        /// </summary>
        [Fact]
        public void MaxHpTest()
        {
            // TODO unit test for the property 'MaxHp'
        }

        /// <summary>
        /// Test the property 'Haste'
        /// </summary>
        [Fact]
        public void HasteTest()
        {
            // TODO unit test for the property 'Haste'
        }

        /// <summary>
        /// Test the property 'CriticalStrike'
        /// </summary>
        [Fact]
        public void CriticalStrikeTest()
        {
            // TODO unit test for the property 'CriticalStrike'
        }

        /// <summary>
        /// Test the property 'Wisdom'
        /// </summary>
        [Fact]
        public void WisdomTest()
        {
            // TODO unit test for the property 'Wisdom'
        }

        /// <summary>
        /// Test the property 'Prospecting'
        /// </summary>
        [Fact]
        public void ProspectingTest()
        {
            // TODO unit test for the property 'Prospecting'
        }

        /// <summary>
        /// Test the property 'Initiative'
        /// </summary>
        [Fact]
        public void InitiativeTest()
        {
            // TODO unit test for the property 'Initiative'
        }

        /// <summary>
        /// Test the property 'Threat'
        /// </summary>
        [Fact]
        public void ThreatTest()
        {
            // TODO unit test for the property 'Threat'
        }

        /// <summary>
        /// Test the property 'AttackFire'
        /// </summary>
        [Fact]
        public void AttackFireTest()
        {
            // TODO unit test for the property 'AttackFire'
        }

        /// <summary>
        /// Test the property 'AttackEarth'
        /// </summary>
        [Fact]
        public void AttackEarthTest()
        {
            // TODO unit test for the property 'AttackEarth'
        }

        /// <summary>
        /// Test the property 'AttackWater'
        /// </summary>
        [Fact]
        public void AttackWaterTest()
        {
            // TODO unit test for the property 'AttackWater'
        }

        /// <summary>
        /// Test the property 'AttackAir'
        /// </summary>
        [Fact]
        public void AttackAirTest()
        {
            // TODO unit test for the property 'AttackAir'
        }

        /// <summary>
        /// Test the property 'Dmg'
        /// </summary>
        [Fact]
        public void DmgTest()
        {
            // TODO unit test for the property 'Dmg'
        }

        /// <summary>
        /// Test the property 'DmgFire'
        /// </summary>
        [Fact]
        public void DmgFireTest()
        {
            // TODO unit test for the property 'DmgFire'
        }

        /// <summary>
        /// Test the property 'DmgEarth'
        /// </summary>
        [Fact]
        public void DmgEarthTest()
        {
            // TODO unit test for the property 'DmgEarth'
        }

        /// <summary>
        /// Test the property 'DmgWater'
        /// </summary>
        [Fact]
        public void DmgWaterTest()
        {
            // TODO unit test for the property 'DmgWater'
        }

        /// <summary>
        /// Test the property 'DmgAir'
        /// </summary>
        [Fact]
        public void DmgAirTest()
        {
            // TODO unit test for the property 'DmgAir'
        }

        /// <summary>
        /// Test the property 'ResFire'
        /// </summary>
        [Fact]
        public void ResFireTest()
        {
            // TODO unit test for the property 'ResFire'
        }

        /// <summary>
        /// Test the property 'ResEarth'
        /// </summary>
        [Fact]
        public void ResEarthTest()
        {
            // TODO unit test for the property 'ResEarth'
        }

        /// <summary>
        /// Test the property 'ResWater'
        /// </summary>
        [Fact]
        public void ResWaterTest()
        {
            // TODO unit test for the property 'ResWater'
        }

        /// <summary>
        /// Test the property 'ResAir'
        /// </summary>
        [Fact]
        public void ResAirTest()
        {
            // TODO unit test for the property 'ResAir'
        }

        /// <summary>
        /// Test the property 'Effects'
        /// </summary>
        [Fact]
        public void EffectsTest()
        {
            // TODO unit test for the property 'Effects'
        }

        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Fact]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }

        /// <summary>
        /// Test the property 'Y'
        /// </summary>
        [Fact]
        public void YTest()
        {
            // TODO unit test for the property 'Y'
        }

        /// <summary>
        /// Test the property 'Layer'
        /// </summary>
        [Fact]
        public void LayerTest()
        {
            // TODO unit test for the property 'Layer'
        }

        /// <summary>
        /// Test the property 'MapId'
        /// </summary>
        [Fact]
        public void MapIdTest()
        {
            // TODO unit test for the property 'MapId'
        }

        /// <summary>
        /// Test the property 'Cooldown'
        /// </summary>
        [Fact]
        public void CooldownTest()
        {
            // TODO unit test for the property 'Cooldown'
        }

        /// <summary>
        /// Test the property 'CooldownExpiration'
        /// </summary>
        [Fact]
        public void CooldownExpirationTest()
        {
            // TODO unit test for the property 'CooldownExpiration'
        }

        /// <summary>
        /// Test the property 'WeaponSlot'
        /// </summary>
        [Fact]
        public void WeaponSlotTest()
        {
            // TODO unit test for the property 'WeaponSlot'
        }

        /// <summary>
        /// Test the property 'RuneSlot'
        /// </summary>
        [Fact]
        public void RuneSlotTest()
        {
            // TODO unit test for the property 'RuneSlot'
        }

        /// <summary>
        /// Test the property 'ShieldSlot'
        /// </summary>
        [Fact]
        public void ShieldSlotTest()
        {
            // TODO unit test for the property 'ShieldSlot'
        }

        /// <summary>
        /// Test the property 'HelmetSlot'
        /// </summary>
        [Fact]
        public void HelmetSlotTest()
        {
            // TODO unit test for the property 'HelmetSlot'
        }

        /// <summary>
        /// Test the property 'BodyArmorSlot'
        /// </summary>
        [Fact]
        public void BodyArmorSlotTest()
        {
            // TODO unit test for the property 'BodyArmorSlot'
        }

        /// <summary>
        /// Test the property 'LegArmorSlot'
        /// </summary>
        [Fact]
        public void LegArmorSlotTest()
        {
            // TODO unit test for the property 'LegArmorSlot'
        }

        /// <summary>
        /// Test the property 'BootsSlot'
        /// </summary>
        [Fact]
        public void BootsSlotTest()
        {
            // TODO unit test for the property 'BootsSlot'
        }

        /// <summary>
        /// Test the property 'Ring1Slot'
        /// </summary>
        [Fact]
        public void Ring1SlotTest()
        {
            // TODO unit test for the property 'Ring1Slot'
        }

        /// <summary>
        /// Test the property 'Ring2Slot'
        /// </summary>
        [Fact]
        public void Ring2SlotTest()
        {
            // TODO unit test for the property 'Ring2Slot'
        }

        /// <summary>
        /// Test the property 'AmuletSlot'
        /// </summary>
        [Fact]
        public void AmuletSlotTest()
        {
            // TODO unit test for the property 'AmuletSlot'
        }

        /// <summary>
        /// Test the property 'Artifact1Slot'
        /// </summary>
        [Fact]
        public void Artifact1SlotTest()
        {
            // TODO unit test for the property 'Artifact1Slot'
        }

        /// <summary>
        /// Test the property 'Artifact2Slot'
        /// </summary>
        [Fact]
        public void Artifact2SlotTest()
        {
            // TODO unit test for the property 'Artifact2Slot'
        }

        /// <summary>
        /// Test the property 'Artifact3Slot'
        /// </summary>
        [Fact]
        public void Artifact3SlotTest()
        {
            // TODO unit test for the property 'Artifact3Slot'
        }

        /// <summary>
        /// Test the property 'Utility1Slot'
        /// </summary>
        [Fact]
        public void Utility1SlotTest()
        {
            // TODO unit test for the property 'Utility1Slot'
        }

        /// <summary>
        /// Test the property 'Utility1SlotQuantity'
        /// </summary>
        [Fact]
        public void Utility1SlotQuantityTest()
        {
            // TODO unit test for the property 'Utility1SlotQuantity'
        }

        /// <summary>
        /// Test the property 'Utility2Slot'
        /// </summary>
        [Fact]
        public void Utility2SlotTest()
        {
            // TODO unit test for the property 'Utility2Slot'
        }

        /// <summary>
        /// Test the property 'Utility2SlotQuantity'
        /// </summary>
        [Fact]
        public void Utility2SlotQuantityTest()
        {
            // TODO unit test for the property 'Utility2SlotQuantity'
        }

        /// <summary>
        /// Test the property 'BagSlot'
        /// </summary>
        [Fact]
        public void BagSlotTest()
        {
            // TODO unit test for the property 'BagSlot'
        }

        /// <summary>
        /// Test the property 'Task'
        /// </summary>
        [Fact]
        public void TaskTest()
        {
            // TODO unit test for the property 'Task'
        }

        /// <summary>
        /// Test the property 'TaskType'
        /// </summary>
        [Fact]
        public void TaskTypeTest()
        {
            // TODO unit test for the property 'TaskType'
        }

        /// <summary>
        /// Test the property 'TaskProgress'
        /// </summary>
        [Fact]
        public void TaskProgressTest()
        {
            // TODO unit test for the property 'TaskProgress'
        }

        /// <summary>
        /// Test the property 'TaskTotal'
        /// </summary>
        [Fact]
        public void TaskTotalTest()
        {
            // TODO unit test for the property 'TaskTotal'
        }

        /// <summary>
        /// Test the property 'InventoryMaxItems'
        /// </summary>
        [Fact]
        public void InventoryMaxItemsTest()
        {
            // TODO unit test for the property 'InventoryMaxItems'
        }

        /// <summary>
        /// Test the property 'Inventory'
        /// </summary>
        [Fact]
        public void InventoryTest()
        {
            // TODO unit test for the property 'Inventory'
        }
    }
}
