/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArtifactsMmoClient.Model;
using ArtifactsMmoClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArtifactsMmoClient.Test.Model
{
    /// <summary>
    ///  Class for testing ClaimPendingItemDataSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClaimPendingItemDataSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClaimPendingItemDataSchema
        //private ClaimPendingItemDataSchema instance;

        public ClaimPendingItemDataSchemaTests()
        {
            // TODO uncomment below to create an instance of ClaimPendingItemDataSchema
            //instance = new ClaimPendingItemDataSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClaimPendingItemDataSchema
        /// </summary>
        [Fact]
        public void ClaimPendingItemDataSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClaimPendingItemDataSchema
            //Assert.IsType<ClaimPendingItemDataSchema>(instance);
        }

        /// <summary>
        /// Test the property 'Cooldown'
        /// </summary>
        [Fact]
        public void CooldownTest()
        {
            // TODO unit test for the property 'Cooldown'
        }

        /// <summary>
        /// Test the property 'Item'
        /// </summary>
        [Fact]
        public void ItemTest()
        {
            // TODO unit test for the property 'Item'
        }

        /// <summary>
        /// Test the property 'Character'
        /// </summary>
        [Fact]
        public void CharacterTest()
        {
            // TODO unit test for the property 'Character'
        }
    }
}
