/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArtifactsMmoClient.Model;
using ArtifactsMmoClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArtifactsMmoClient.Test.Model
{
    /// <summary>
    ///  Class for testing DropRateSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DropRateSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DropRateSchema
        //private DropRateSchema instance;

        public DropRateSchemaTests()
        {
            // TODO uncomment below to create an instance of DropRateSchema
            //instance = new DropRateSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DropRateSchema
        /// </summary>
        [Fact]
        public void DropRateSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" DropRateSchema
            //Assert.IsType<DropRateSchema>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Rate'
        /// </summary>
        [Fact]
        public void RateTest()
        {
            // TODO unit test for the property 'Rate'
        }

        /// <summary>
        /// Test the property 'MinQuantity'
        /// </summary>
        [Fact]
        public void MinQuantityTest()
        {
            // TODO unit test for the property 'MinQuantity'
        }

        /// <summary>
        /// Test the property 'MaxQuantity'
        /// </summary>
        [Fact]
        public void MaxQuantityTest()
        {
            // TODO unit test for the property 'MaxQuantity'
        }
    }
}
