/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArtifactsMmoClient.Model;
using ArtifactsMmoClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArtifactsMmoClient.Test.Model
{
    /// <summary>
    ///  Class for testing GECancelOrderSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GECancelOrderSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GECancelOrderSchema
        //private GECancelOrderSchema instance;

        public GECancelOrderSchemaTests()
        {
            // TODO uncomment below to create an instance of GECancelOrderSchema
            //instance = new GECancelOrderSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GECancelOrderSchema
        /// </summary>
        [Fact]
        public void GECancelOrderSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" GECancelOrderSchema
            //Assert.IsType<GECancelOrderSchema>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
