/*
 * Artifacts API
 *
 * Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 7.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArtifactsMmoClient.Model;
using ArtifactsMmoClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArtifactsMmoClient.Test.Model
{
    /// <summary>
    ///  Class for testing GEFillBuyOrderSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GEFillBuyOrderSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GEFillBuyOrderSchema
        //private GEFillBuyOrderSchema instance;

        public GEFillBuyOrderSchemaTests()
        {
            // TODO uncomment below to create an instance of GEFillBuyOrderSchema
            //instance = new GEFillBuyOrderSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GEFillBuyOrderSchema
        /// </summary>
        [Fact]
        public void GEFillBuyOrderSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" GEFillBuyOrderSchema
            //Assert.IsType<GEFillBuyOrderSchema>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
    }
}
